// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: banks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBank = `-- name: CreateBank :one


INSERT INTO banks (owner_user_id, name)
VALUES ($1, $2)
RETURNING id, owner_user_id, name, is_active, created_at
`

type CreateBankParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
}

// Queries de banks. Los bancos son del user (owner_user_id),
// nunca se borran: toggle de is_active.
func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRow(ctx, createBank, arg.OwnerUserID, arg.Name)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBankByID = `-- name: GetBankByID :one
SELECT id, owner_user_id, name, is_active, created_at FROM banks WHERE id = $1
`

func (q *Queries) GetBankByID(ctx context.Context, id uuid.UUID) (Bank, error) {
	row := q.db.QueryRow(ctx, getBankByID, id)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBanksByOwner = `-- name: ListBanksByOwner :many
SELECT id, owner_user_id, name, is_active, created_at FROM banks
WHERE owner_user_id = $1 AND is_active = true
ORDER BY name ASC
`

// Lista los bancos activos del user, orden estable por nombre.
// Si algún día hace falta mostrar los desactivados, se agrega otra query.
func (q *Queries) ListBanksByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Bank, error) {
	rows, err := q.db.Query(ctx, listBanksByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bank{}
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBankActive = `-- name: SetBankActive :one
UPDATE banks
SET is_active = $2
WHERE id = $1
RETURNING id, owner_user_id, name, is_active, created_at
`

type SetBankActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

// Activa o desactiva un banco. El ON DELETE SET NULL en payment_methods.bank_id
// NO se dispara acá (no borramos la fila), así que los métodos siguen
// asociados al banco aunque el banco esté inactivo.
func (q *Queries) SetBankActive(ctx context.Context, arg SetBankActiveParams) (Bank, error) {
	row := q.db.QueryRow(ctx, setBankActive, arg.ID, arg.IsActive)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateBankName = `-- name: UpdateBankName :one
UPDATE banks
SET name = $2
WHERE id = $1
RETURNING id, owner_user_id, name, is_active, created_at
`

type UpdateBankNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Solo permite cambiar el nombre (único campo editable del modelo).
func (q *Queries) UpdateBankName(ctx context.Context, arg UpdateBankNameParams) (Bank, error) {
	row := q.db.QueryRow(ctx, updateBankName, arg.ID, arg.Name)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
