// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (household_id, name, icon, color)
VALUES ($1, $2, $3, $4)
RETURNING id, household_id, name, icon, color, created_at, updated_at
`

type CreateCategoryParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Icon        string    `json:"icon"`
	Color       string    `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.HouseholdID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, household_id, name, icon, color, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByHousehold = `-- name: ListCategoriesByHousehold :many
SELECT id, household_id, name, icon, color, created_at, updated_at FROM categories
WHERE household_id = $1
ORDER BY name ASC
`

func (q *Queries) ListCategoriesByHousehold(ctx context.Context, householdID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    icon = $3,
    color = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, name, icon, color, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Icon  string    `json:"icon"`
	Color string    `json:"color"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
