// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_card_periods.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCreditCardPeriod = `-- name: DeleteCreditCardPeriod :exec
DELETE FROM credit_card_periods
WHERE credit_card_id = $1 AND period_ym = $2
`

type DeleteCreditCardPeriodParams struct {
	CreditCardID uuid.UUID `json:"credit_card_id"`
	PeriodYm     string    `json:"period_ym"`
}

func (q *Queries) DeleteCreditCardPeriod(ctx context.Context, arg DeleteCreditCardPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteCreditCardPeriod, arg.CreditCardID, arg.PeriodYm)
	return err
}

const getCreditCardPeriod = `-- name: GetCreditCardPeriod :one
SELECT credit_card_id, period_ym, closing_date, due_date, created_at, updated_at FROM credit_card_periods
WHERE credit_card_id = $1 AND period_ym = $2
`

type GetCreditCardPeriodParams struct {
	CreditCardID uuid.UUID `json:"credit_card_id"`
	PeriodYm     string    `json:"period_ym"`
}

func (q *Queries) GetCreditCardPeriod(ctx context.Context, arg GetCreditCardPeriodParams) (CreditCardPeriod, error) {
	row := q.db.QueryRow(ctx, getCreditCardPeriod, arg.CreditCardID, arg.PeriodYm)
	var i CreditCardPeriod
	err := row.Scan(
		&i.CreditCardID,
		&i.PeriodYm,
		&i.ClosingDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCreditCardPeriod = `-- name: GetLatestCreditCardPeriod :one
SELECT credit_card_id, period_ym, closing_date, due_date, created_at, updated_at FROM credit_card_periods
WHERE credit_card_id = $1
ORDER BY period_ym DESC
LIMIT 1
`

func (q *Queries) GetLatestCreditCardPeriod(ctx context.Context, creditCardID uuid.UUID) (CreditCardPeriod, error) {
	row := q.db.QueryRow(ctx, getLatestCreditCardPeriod, creditCardID)
	var i CreditCardPeriod
	err := row.Scan(
		&i.CreditCardID,
		&i.PeriodYm,
		&i.ClosingDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditCardPeriods = `-- name: ListCreditCardPeriods :many
SELECT credit_card_id, period_ym, closing_date, due_date, created_at, updated_at FROM credit_card_periods
WHERE credit_card_id = $1
ORDER BY period_ym DESC
`

func (q *Queries) ListCreditCardPeriods(ctx context.Context, creditCardID uuid.UUID) ([]CreditCardPeriod, error) {
	rows, err := q.db.Query(ctx, listCreditCardPeriods, creditCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditCardPeriod{}
	for rows.Next() {
		var i CreditCardPeriod
		if err := rows.Scan(
			&i.CreditCardID,
			&i.PeriodYm,
			&i.ClosingDate,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreditCardPeriod = `-- name: UpsertCreditCardPeriod :one
INSERT INTO credit_card_periods (credit_card_id, period_ym, closing_date, due_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (credit_card_id, period_ym) DO UPDATE
SET closing_date = EXCLUDED.closing_date,
    due_date = EXCLUDED.due_date,
    updated_at = NOW()
RETURNING credit_card_id, period_ym, closing_date, due_date, created_at, updated_at
`

type UpsertCreditCardPeriodParams struct {
	CreditCardID uuid.UUID   `json:"credit_card_id"`
	PeriodYm     string      `json:"period_ym"`
	ClosingDate  pgtype.Date `json:"closing_date"`
	DueDate      pgtype.Date `json:"due_date"`
}

func (q *Queries) UpsertCreditCardPeriod(ctx context.Context, arg UpsertCreditCardPeriodParams) (CreditCardPeriod, error) {
	row := q.db.QueryRow(ctx, upsertCreditCardPeriod,
		arg.CreditCardID,
		arg.PeriodYm,
		arg.ClosingDate,
		arg.DueDate,
	)
	var i CreditCardPeriod
	err := row.Scan(
		&i.CreditCardID,
		&i.PeriodYm,
		&i.ClosingDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
