// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_cards.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditCard = `-- name: CreateCreditCard :one


INSERT INTO credit_cards (
    payment_method_id,
    alias,
    last_four,
    default_closing_day,
    default_due_day,
    debit_payment_method_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_method_id, alias, last_four, default_closing_day, default_due_day, debit_payment_method_id, created_at
`

type CreateCreditCardParams struct {
	PaymentMethodID      uuid.UUID   `json:"payment_method_id"`
	Alias                string      `json:"alias"`
	LastFour             pgtype.Text `json:"last_four"`
	DefaultClosingDay    int32       `json:"default_closing_day"`
	DefaultDueDay        int32       `json:"default_due_day"`
	DebitPaymentMethodID *uuid.UUID  `json:"debit_payment_method_id"`
}

// Queries de credit_cards. 1-a-1 con payment_methods de kind='credit'.
// Se crean siempre en la misma transacción que el payment_method (opción A).
func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCreditCard,
		arg.PaymentMethodID,
		arg.Alias,
		arg.LastFour,
		arg.DefaultClosingDay,
		arg.DefaultDueDay,
		arg.DebitPaymentMethodID,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.PaymentMethodID,
		&i.Alias,
		&i.LastFour,
		&i.DefaultClosingDay,
		&i.DefaultDueDay,
		&i.DebitPaymentMethodID,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditCardByPaymentMethodID = `-- name: GetCreditCardByPaymentMethodID :one
SELECT id, payment_method_id, alias, last_four, default_closing_day, default_due_day, debit_payment_method_id, created_at FROM credit_cards WHERE payment_method_id = $1
`

// Devuelve el detalle de tarjeta asociado al payment_method dado.
// Si no existe (método no es credit) → pgx.ErrNoRows → repo mapea a ErrNotFound.
func (q *Queries) GetCreditCardByPaymentMethodID(ctx context.Context, paymentMethodID uuid.UUID) (CreditCard, error) {
	row := q.db.QueryRow(ctx, getCreditCardByPaymentMethodID, paymentMethodID)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.PaymentMethodID,
		&i.Alias,
		&i.LastFour,
		&i.DefaultClosingDay,
		&i.DefaultDueDay,
		&i.DebitPaymentMethodID,
		&i.CreatedAt,
	)
	return i, err
}

const listCreditCardsByOwner = `-- name: ListCreditCardsByOwner :many
SELECT cc.id, cc.payment_method_id, cc.alias, cc.last_four, cc.default_closing_day, cc.default_due_day, cc.debit_payment_method_id, cc.created_at, pm.id, pm.owner_user_id, pm.bank_id, pm.name, pm.kind, pm.allows_installments, pm.is_active, pm.created_at
FROM credit_cards cc
INNER JOIN payment_methods pm ON pm.id = cc.payment_method_id
WHERE pm.owner_user_id = $1
  AND pm.is_active = true
ORDER BY cc.alias ASC
`

type ListCreditCardsByOwnerRow struct {
	CreditCard    CreditCard    `json:"credit_card"`
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// Lista las tarjetas activas del user con el payment_method embebido,
// para evitar N+1 en el frontend (una sola llamada devuelve todo).
// Filtra por payment_method.is_active = true: una tarjeta sin método
// activo no se muestra.
func (q *Queries) ListCreditCardsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListCreditCardsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listCreditCardsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditCardsByOwnerRow{}
	for rows.Next() {
		var i ListCreditCardsByOwnerRow
		if err := rows.Scan(
			&i.CreditCard.ID,
			&i.CreditCard.PaymentMethodID,
			&i.CreditCard.Alias,
			&i.CreditCard.LastFour,
			&i.CreditCard.DefaultClosingDay,
			&i.CreditCard.DefaultDueDay,
			&i.CreditCard.DebitPaymentMethodID,
			&i.CreditCard.CreatedAt,
			&i.PaymentMethod.ID,
			&i.PaymentMethod.OwnerUserID,
			&i.PaymentMethod.BankID,
			&i.PaymentMethod.Name,
			&i.PaymentMethod.Kind,
			&i.PaymentMethod.AllowsInstallments,
			&i.PaymentMethod.IsActive,
			&i.PaymentMethod.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditCard = `-- name: UpdateCreditCard :one
UPDATE credit_cards
SET alias                   = $2,
    last_four               = $3,
    default_closing_day     = $4,
    default_due_day         = $5,
    debit_payment_method_id = $6
WHERE id = $1
RETURNING id, payment_method_id, alias, last_four, default_closing_day, default_due_day, debit_payment_method_id, created_at
`

type UpdateCreditCardParams struct {
	ID                   uuid.UUID   `json:"id"`
	Alias                string      `json:"alias"`
	LastFour             pgtype.Text `json:"last_four"`
	DefaultClosingDay    int32       `json:"default_closing_day"`
	DefaultDueDay        int32       `json:"default_due_day"`
	DebitPaymentMethodID *uuid.UUID  `json:"debit_payment_method_id"`
}

// Alias, last_four y ciclo son editables. payment_method_id es inmutable.
// debit_payment_method_id cambiable (ej: cambiás la cuenta de débito automático).
// La validación "mismo owner / no auto-referencia" se hace en el service.
func (q *Queries) UpdateCreditCard(ctx context.Context, arg UpdateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, updateCreditCard,
		arg.ID,
		arg.Alias,
		arg.LastFour,
		arg.DefaultClosingDay,
		arg.DefaultDueDay,
		arg.DebitPaymentMethodID,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.PaymentMethodID,
		&i.Alias,
		&i.LastFour,
		&i.DefaultClosingDay,
		&i.DefaultDueDay,
		&i.DebitPaymentMethodID,
		&i.CreatedAt,
	)
	return i, err
}
