// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one


INSERT INTO email_verifications (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries de email_verifications + flag de verificación en users.
func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationByTokenHash = `-- name: GetEmailVerificationByTokenHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verifications WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByTokenHash, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateActiveEmailVerificationsForUser = `-- name: InvalidateActiveEmailVerificationsForUser :exec
UPDATE email_verifications
SET used_at = now()
WHERE user_id = $1
  AND used_at IS NULL
`

// Al emitir un nuevo token, invalidamos los anteriores del user.
func (q *Queries) InvalidateActiveEmailVerificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailVerificationsForUser, userID)
	return err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :one
UPDATE email_verifications
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

// Single-use condicional: solo matchea si aún no fue usado y no expiró.
func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, id uuid.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, markEmailVerificationUsed, id)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = now(),
    updated_at = now()
WHERE id = $1
  AND email_verified_at IS NULL
`

// Idempotente: si ya estaba verificado no hace nada.
func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}
