// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestExchangeRate = `-- name: GetLatestExchangeRate :one
SELECT currency, source, last_update, rate_avg, rate_buy, rate_sell, fetched_at
FROM exchange_rates
WHERE currency = $1 AND source = $2
ORDER BY last_update DESC
LIMIT 1
`

type GetLatestExchangeRateParams struct {
	Currency string `json:"currency"`
	Source   string `json:"source"`
}

func (q *Queries) GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestExchangeRate, arg.Currency, arg.Source)
	var i ExchangeRate
	err := row.Scan(
		&i.Currency,
		&i.Source,
		&i.LastUpdate,
		&i.RateAvg,
		&i.RateBuy,
		&i.RateSell,
		&i.FetchedAt,
	)
	return i, err
}

const listLatestExchangeRates = `-- name: ListLatestExchangeRates :many
SELECT DISTINCT ON (currency, source)
    currency, source, last_update, rate_avg, rate_buy, rate_sell, fetched_at
FROM exchange_rates
ORDER BY currency, source, last_update DESC
`

// Devuelve la última fila por (currency, source) usando DISTINCT ON.
// Útil para el endpoint /current y para rehidratar el caché al arrancar.
func (q *Queries) ListLatestExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listLatestExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.Currency,
			&i.Source,
			&i.LastUpdate,
			&i.RateAvg,
			&i.RateBuy,
			&i.RateSell,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (currency, source, last_update, rate_avg, rate_buy, rate_sell)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (currency, source, last_update) DO NOTHING
`

type UpsertExchangeRateParams struct {
	Currency   string             `json:"currency"`
	Source     string             `json:"source"`
	LastUpdate pgtype.Timestamptz `json:"last_update"`
	RateAvg    pgtype.Numeric     `json:"rate_avg"`
	RateBuy    pgtype.Numeric     `json:"rate_buy"`
	RateSell   pgtype.Numeric     `json:"rate_sell"`
}

// El worker corre cada 15min aunque bluelytics no tenga dato nuevo
// (fines de semana, feriados). ON CONFLICT DO NOTHING evita duplicar.
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.Currency,
		arg.Source,
		arg.LastUpdate,
		arg.RateAvg,
		arg.RateBuy,
		arg.RateSell,
	)
	return err
}
