// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesByHousehold = `-- name: CountExpensesByHousehold :one
SELECT COUNT(*)::bigint
FROM expenses
WHERE household_id = $1
  AND ($2::uuid IS NULL OR category_id = $2::uuid)
  AND ($3::uuid IS NULL OR payment_method_id = $3::uuid)
  AND ($4::date IS NULL OR spent_at >= $4::date)
  AND ($5::date IS NULL OR spent_at <= $5::date)
`

type CountExpensesByHouseholdParams struct {
	HouseholdID     uuid.UUID   `json:"household_id"`
	CategoryID      *uuid.UUID  `json:"category_id"`
	PaymentMethodID *uuid.UUID  `json:"payment_method_id"`
	FromDate        pgtype.Date `json:"from_date"`
	ToDate          pgtype.Date `json:"to_date"`
}

func (q *Queries) CountExpensesByHousehold(ctx context.Context, arg CountExpensesByHouseholdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesByHousehold,
		arg.HouseholdID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.FromDate,
		arg.ToDate,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    household_id, created_by, category_id, payment_method_id,
    amount, currency, amount_base, base_currency, rate_used, rate_at,
    description, spent_at, installments, is_shared
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, household_id, created_by, category_id, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, description, spent_at, installments, is_shared, created_at, updated_at
`

type CreateExpenseParams struct {
	HouseholdID     uuid.UUID          `json:"household_id"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CategoryID      *uuid.UUID         `json:"category_id"`
	PaymentMethodID uuid.UUID          `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	AmountBase      pgtype.Numeric     `json:"amount_base"`
	BaseCurrency    string             `json:"base_currency"`
	RateUsed        pgtype.Numeric     `json:"rate_used"`
	RateAt          pgtype.Timestamptz `json:"rate_at"`
	Description     string             `json:"description"`
	SpentAt         pgtype.Date        `json:"spent_at"`
	Installments    int32              `json:"installments"`
	IsShared        bool               `json:"is_shared"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.HouseholdID,
		arg.CreatedBy,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.AmountBase,
		arg.BaseCurrency,
		arg.RateUsed,
		arg.RateAt,
		arg.Description,
		arg.SpentAt,
		arg.Installments,
		arg.IsShared,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Description,
		&i.SpentAt,
		&i.Installments,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallment = `-- name: CreateInstallment :one

INSERT INTO expense_installments (
    expense_id, installment_number,
    installment_amount, installment_amount_base,
    billing_date, due_date, is_paid, paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, expense_id, installment_number, installment_amount, installment_amount_base, billing_date, due_date, is_paid, paid_at, created_at, updated_at
`

type CreateInstallmentParams struct {
	ExpenseID             uuid.UUID          `json:"expense_id"`
	InstallmentNumber     int32              `json:"installment_number"`
	InstallmentAmount     pgtype.Numeric     `json:"installment_amount"`
	InstallmentAmountBase pgtype.Numeric     `json:"installment_amount_base"`
	BillingDate           pgtype.Date        `json:"billing_date"`
	DueDate               pgtype.Date        `json:"due_date"`
	IsPaid                bool               `json:"is_paid"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
}

// ===== installments =====
func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (ExpenseInstallment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.ExpenseID,
		arg.InstallmentNumber,
		arg.InstallmentAmount,
		arg.InstallmentAmountBase,
		arg.BillingDate,
		arg.DueDate,
		arg.IsPaid,
		arg.PaidAt,
	)
	var i ExpenseInstallment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.InstallmentAmount,
		&i.InstallmentAmountBase,
		&i.BillingDate,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallmentShare = `-- name: CreateInstallmentShare :exec

INSERT INTO expense_installment_shares (installment_id, user_id, amount_base_owed)
VALUES ($1, $2, $3)
`

type CreateInstallmentShareParams struct {
	InstallmentID  uuid.UUID      `json:"installment_id"`
	UserID         uuid.UUID      `json:"user_id"`
	AmountBaseOwed pgtype.Numeric `json:"amount_base_owed"`
}

// ===== shares =====
func (q *Queries) CreateInstallmentShare(ctx context.Context, arg CreateInstallmentShareParams) error {
	_, err := q.db.Exec(ctx, createInstallmentShare, arg.InstallmentID, arg.UserID, arg.AmountBaseOwed)
	return err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, household_id, created_by, category_id, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, description, spent_at, installments, is_shared, created_at, updated_at FROM expenses WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Description,
		&i.SpentAt,
		&i.Installments,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallmentByExpenseAndNumber = `-- name: GetInstallmentByExpenseAndNumber :one
SELECT id, expense_id, installment_number, installment_amount, installment_amount_base, billing_date, due_date, is_paid, paid_at, created_at, updated_at FROM expense_installments
WHERE expense_id = $1 AND installment_number = $2
`

type GetInstallmentByExpenseAndNumberParams struct {
	ExpenseID         uuid.UUID `json:"expense_id"`
	InstallmentNumber int32     `json:"installment_number"`
}

func (q *Queries) GetInstallmentByExpenseAndNumber(ctx context.Context, arg GetInstallmentByExpenseAndNumberParams) (ExpenseInstallment, error) {
	row := q.db.QueryRow(ctx, getInstallmentByExpenseAndNumber, arg.ExpenseID, arg.InstallmentNumber)
	var i ExpenseInstallment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.InstallmentAmount,
		&i.InstallmentAmountBase,
		&i.BillingDate,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpensesByHousehold = `-- name: ListExpensesByHousehold :many
SELECT id, household_id, created_by, category_id, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, description, spent_at, installments, is_shared, created_at, updated_at
FROM expenses
WHERE household_id = $1
  AND ($4::uuid IS NULL OR category_id = $4::uuid)
  AND ($5::uuid IS NULL OR payment_method_id = $5::uuid)
  AND ($6::date IS NULL OR spent_at >= $6::date)
  AND ($7::date IS NULL OR spent_at <= $7::date)
ORDER BY spent_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListExpensesByHouseholdParams struct {
	HouseholdID     uuid.UUID   `json:"household_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	CategoryID      *uuid.UUID  `json:"category_id"`
	PaymentMethodID *uuid.UUID  `json:"payment_method_id"`
	FromDate        pgtype.Date `json:"from_date"`
	ToDate          pgtype.Date `json:"to_date"`
}

// Filtros opcionales: categoryId, paymentMethodId, desde/hasta (fechas).
// Paginación por offset/limit simple. Cuando el volumen crezca, migrar a keyset.
func (q *Queries) ListExpensesByHousehold(ctx context.Context, arg ListExpensesByHouseholdParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByHousehold,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CreatedBy,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.BaseCurrency,
			&i.RateUsed,
			&i.RateAt,
			&i.Description,
			&i.SpentAt,
			&i.Installments,
			&i.IsShared,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsByExpense = `-- name: ListInstallmentsByExpense :many
SELECT id, expense_id, installment_number, installment_amount, installment_amount_base, billing_date, due_date, is_paid, paid_at, created_at, updated_at FROM expense_installments
WHERE expense_id = $1
ORDER BY installment_number ASC
`

func (q *Queries) ListInstallmentsByExpense(ctx context.Context, expenseID uuid.UUID) ([]ExpenseInstallment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseInstallment{}
	for rows.Next() {
		var i ExpenseInstallment
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.InstallmentNumber,
			&i.InstallmentAmount,
			&i.InstallmentAmountBase,
			&i.BillingDate,
			&i.DueDate,
			&i.IsPaid,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByExpense = `-- name: ListSharesByExpense :many
SELECT s.installment_id, s.user_id, s.amount_base_owed
FROM expense_installment_shares s
JOIN expense_installments i ON i.id = s.installment_id
WHERE i.expense_id = $1
ORDER BY i.installment_number ASC
`

func (q *Queries) ListSharesByExpense(ctx context.Context, expenseID uuid.UUID) ([]ExpenseInstallmentShare, error) {
	rows, err := q.db.Query(ctx, listSharesByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseInstallmentShare{}
	for rows.Next() {
		var i ExpenseInstallmentShare
		if err := rows.Scan(&i.InstallmentID, &i.UserID, &i.AmountBaseOwed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByInstallment = `-- name: ListSharesByInstallment :many
SELECT installment_id, user_id, amount_base_owed FROM expense_installment_shares
WHERE installment_id = $1
`

func (q *Queries) ListSharesByInstallment(ctx context.Context, installmentID uuid.UUID) ([]ExpenseInstallmentShare, error) {
	rows, err := q.db.Query(ctx, listSharesByInstallment, installmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseInstallmentShare{}
	for rows.Next() {
		var i ExpenseInstallmentShare
		if err := rows.Scan(&i.InstallmentID, &i.UserID, &i.AmountBaseOwed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstallmentPaid = `-- name: SetInstallmentPaid :one
UPDATE expense_installments
SET is_paid = $2,
    paid_at = CASE WHEN $2 THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, expense_id, installment_number, installment_amount, installment_amount_base, billing_date, due_date, is_paid, paid_at, created_at, updated_at
`

type SetInstallmentPaidParams struct {
	ID     uuid.UUID `json:"id"`
	IsPaid bool      `json:"is_paid"`
}

func (q *Queries) SetInstallmentPaid(ctx context.Context, arg SetInstallmentPaidParams) (ExpenseInstallment, error) {
	row := q.db.QueryRow(ctx, setInstallmentPaid, arg.ID, arg.IsPaid)
	var i ExpenseInstallment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.InstallmentAmount,
		&i.InstallmentAmountBase,
		&i.BillingDate,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description = $2,
    spent_at = $3,
    category_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, household_id, created_by, category_id, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, description, spent_at, installments, is_shared, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID   `json:"id"`
	Description string      `json:"description"`
	SpentAt     pgtype.Date `json:"spent_at"`
	CategoryID  *uuid.UUID  `json:"category_id"`
}

// Solo campos editables: description, spent_at, category_id.
// amount/currency/installments NO se editan (borrar y recrear).
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Description,
		arg.SpentAt,
		arg.CategoryID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Description,
		&i.SpentAt,
		&i.Installments,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstallmentDates = `-- name: UpdateInstallmentDates :one
UPDATE expense_installments
SET billing_date = $2,
    due_date = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, expense_id, installment_number, installment_amount, installment_amount_base, billing_date, due_date, is_paid, paid_at, created_at, updated_at
`

type UpdateInstallmentDatesParams struct {
	ID          uuid.UUID   `json:"id"`
	BillingDate pgtype.Date `json:"billing_date"`
	DueDate     pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateInstallmentDates(ctx context.Context, arg UpdateInstallmentDatesParams) (ExpenseInstallment, error) {
	row := q.db.QueryRow(ctx, updateInstallmentDates, arg.ID, arg.BillingDate, arg.DueDate)
	var i ExpenseInstallment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.InstallmentAmount,
		&i.InstallmentAmountBase,
		&i.BillingDate,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
