// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetGoal = `-- name: CreateBudgetGoal :one

INSERT INTO budget_goals (
    household_id, scope, user_id, category_id,
    goal_type, target_amount, currency, period, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, household_id, scope, user_id, category_id, goal_type, target_amount, currency, period, is_active, created_at
`

type CreateBudgetGoalParams struct {
	HouseholdID  uuid.UUID      `json:"household_id"`
	Scope        string         `json:"scope"`
	UserID       *uuid.UUID     `json:"user_id"`
	CategoryID   *uuid.UUID     `json:"category_id"`
	GoalType     string         `json:"goal_type"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	Currency     string         `json:"currency"`
	Period       string         `json:"period"`
	IsActive     bool           `json:"is_active"`
}

// ===================== budget_goals =====================
func (q *Queries) CreateBudgetGoal(ctx context.Context, arg CreateBudgetGoalParams) (BudgetGoal, error) {
	row := q.db.QueryRow(ctx, createBudgetGoal,
		arg.HouseholdID,
		arg.Scope,
		arg.UserID,
		arg.CategoryID,
		arg.GoalType,
		arg.TargetAmount,
		arg.Currency,
		arg.Period,
		arg.IsActive,
	)
	var i BudgetGoal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.CategoryID,
		&i.GoalType,
		&i.TargetAmount,
		&i.Currency,
		&i.Period,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudgetGoal = `-- name: DeleteBudgetGoal :exec
DELETE FROM budget_goals WHERE id = $1
`

func (q *Queries) DeleteBudgetGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudgetGoal, id)
	return err
}

const getBudgetGoalByID = `-- name: GetBudgetGoalByID :one
SELECT id, household_id, scope, user_id, category_id, goal_type, target_amount, currency, period, is_active, created_at FROM budget_goals WHERE id = $1
`

func (q *Queries) GetBudgetGoalByID(ctx context.Context, id uuid.UUID) (BudgetGoal, error) {
	row := q.db.QueryRow(ctx, getBudgetGoalByID, id)
	var i BudgetGoal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.CategoryID,
		&i.GoalType,
		&i.TargetAmount,
		&i.Currency,
		&i.Period,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgetGoalsByHousehold = `-- name: ListBudgetGoalsByHousehold :many
SELECT id, household_id, scope, user_id, category_id, goal_type, target_amount, currency, period, is_active, created_at FROM budget_goals
WHERE household_id = $1
  AND ($2::text IS NULL OR scope = $2::text)
  AND ($3::uuid IS NULL OR user_id = $3::uuid)
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
ORDER BY is_active DESC, created_at DESC
`

type ListBudgetGoalsByHouseholdParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Scope       pgtype.Text `json:"scope"`
	UserID      *uuid.UUID  `json:"user_id"`
	OnlyActive  pgtype.Bool `json:"only_active"`
}

// Filtros opcionales: scope, user_id (cuando scope='user'), is_active.
func (q *Queries) ListBudgetGoalsByHousehold(ctx context.Context, arg ListBudgetGoalsByHouseholdParams) ([]BudgetGoal, error) {
	rows, err := q.db.Query(ctx, listBudgetGoalsByHousehold,
		arg.HouseholdID,
		arg.Scope,
		arg.UserID,
		arg.OnlyActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetGoal{}
	for rows.Next() {
		var i BudgetGoal
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Scope,
			&i.UserID,
			&i.CategoryID,
			&i.GoalType,
			&i.TargetAmount,
			&i.Currency,
			&i.Period,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBudgetGoalActive = `-- name: SetBudgetGoalActive :exec
UPDATE budget_goals SET is_active = $2 WHERE id = $1
`

type SetBudgetGoalActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetBudgetGoalActive(ctx context.Context, arg SetBudgetGoalActiveParams) error {
	_, err := q.db.Exec(ctx, setBudgetGoalActive, arg.ID, arg.IsActive)
	return err
}

const sumIncomesByUserInRange = `-- name: SumIncomesByUserInRange :one
SELECT COALESCE(SUM(amount_base), 0)::numeric AS total_base
FROM incomes
WHERE household_id = $1
  AND received_by = $2
  AND received_at >= $3::date
  AND received_at <= $4::date
`

type SumIncomesByUserInRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	ReceivedBy  uuid.UUID   `json:"received_by"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
}

// Para savings scope=user: total de ingresos de un usuario en el período.
func (q *Queries) SumIncomesByUserInRange(ctx context.Context, arg SumIncomesByUserInRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumIncomesByUserInRange,
		arg.HouseholdID,
		arg.ReceivedBy,
		arg.Column3,
		arg.Column4,
	)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const sumInstallmentsForHouseholdGoal = `-- name: SumInstallmentsForHouseholdGoal :one

SELECT COALESCE(SUM(i.installment_amount_base), 0)::numeric AS total_base
FROM expense_installments i
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND ($4::uuid IS NULL OR e.category_id = $4::uuid)
  AND COALESCE(i.due_date, i.billing_date) >= $2::date
  AND COALESCE(i.due_date, i.billing_date) <= $3::date
`

type SumInstallmentsForHouseholdGoalParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
	CategoryID  *uuid.UUID  `json:"category_id"`
}

// ===================== progress helpers =====================
// Suma base de cuotas del hogar dentro del período, filtrando por categoría
// opcional. Usa COALESCE(due_date, billing_date): crédito cuenta cuando vence,
// el resto cuando se pagó (billing_date = spent_at).
func (q *Queries) SumInstallmentsForHouseholdGoal(ctx context.Context, arg SumInstallmentsForHouseholdGoalParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumInstallmentsForHouseholdGoal,
		arg.HouseholdID,
		arg.Column2,
		arg.Column3,
		arg.CategoryID,
	)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const sumInstallmentsForUserGoal = `-- name: SumInstallmentsForUserGoal :one
SELECT (
    COALESCE((
        SELECT SUM(s.amount_base_owed)
        FROM expense_installment_shares s
        JOIN expense_installments i ON i.id = s.installment_id
        JOIN expenses e ON e.id = i.expense_id
        WHERE e.household_id = $1
          AND e.is_shared = true
          AND s.user_id = $2
          AND ($5::uuid IS NULL OR e.category_id = $5::uuid)
          AND COALESCE(i.due_date, i.billing_date) >= $3::date
          AND COALESCE(i.due_date, i.billing_date) <= $4::date
    ), 0)
    +
    COALESCE((
        SELECT SUM(i.installment_amount_base)
        FROM expense_installments i
        JOIN expenses e ON e.id = i.expense_id
        WHERE e.household_id = $1
          AND e.is_shared = false
          AND e.created_by = $2
          AND ($5::uuid IS NULL OR e.category_id = $5::uuid)
          AND COALESCE(i.due_date, i.billing_date) >= $3::date
          AND COALESCE(i.due_date, i.billing_date) <= $4::date
    ), 0)
)::numeric AS total_base
`

type SumInstallmentsForUserGoalParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
	CategoryID  *uuid.UUID  `json:"category_id"`
}

// Suma la porción del usuario en cuotas del hogar dentro del período.
// Para gastos compartidos: usa expense_installment_shares.
// Para gastos NO compartidos (is_shared=false): cuenta el total si el usuario
// es created_by, porque no hay filas de shares.
func (q *Queries) SumInstallmentsForUserGoal(ctx context.Context, arg SumInstallmentsForUserGoalParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumInstallmentsForUserGoal,
		arg.HouseholdID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.CategoryID,
	)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const updateBudgetGoal = `-- name: UpdateBudgetGoal :one
UPDATE budget_goals
SET category_id   = $2,
    target_amount = $3,
    currency      = $4,
    period        = $5
WHERE id = $1
RETURNING id, household_id, scope, user_id, category_id, goal_type, target_amount, currency, period, is_active, created_at
`

type UpdateBudgetGoalParams struct {
	ID           uuid.UUID      `json:"id"`
	CategoryID   *uuid.UUID     `json:"category_id"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	Currency     string         `json:"currency"`
	Period       string         `json:"period"`
}

// No dejamos cambiar scope/user_id/goal_type — si hay que migrar, borrar y crear.
func (q *Queries) UpdateBudgetGoal(ctx context.Context, arg UpdateBudgetGoalParams) (BudgetGoal, error) {
	row := q.db.QueryRow(ctx, updateBudgetGoal,
		arg.ID,
		arg.CategoryID,
		arg.TargetAmount,
		arg.Currency,
		arg.Period,
	)
	var i BudgetGoal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.CategoryID,
		&i.GoalType,
		&i.TargetAmount,
		&i.Currency,
		&i.Period,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
