// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseholdMember = `-- name: AddHouseholdMember :one


INSERT INTO household_members (household_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING household_id, user_id, role, joined_at
`

type AddHouseholdMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

// ============================================================
// household_members
// ============================================================
func (q *Queries) AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, addHouseholdMember, arg.HouseholdID, arg.UserID, arg.Role)
	var i HouseholdMember
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countHouseholdOwners = `-- name: CountHouseholdOwners :one
SELECT COUNT(*) AS count
FROM household_members
WHERE household_id = $1 AND role = 'owner'
`

// Cuenta los owners vigentes de un hogar. Sirve para invariantes (ej:
// no permitir demotions que dejen 0 owners).
func (q *Queries) CountHouseholdOwners(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHouseholdOwners, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one


INSERT INTO households (name, base_currency, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, base_currency, created_by, created_at, updated_at, deleted_at
`

type CreateHouseholdParams struct {
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

// Queries de households y household_members.
func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.BaseCurrency, arg.CreatedBy)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, base_currency, created_by, created_at, updated_at, deleted_at FROM households WHERE id = $1 AND deleted_at IS NULL
`

// Filtra soft-deleted: un hogar borrado por su owner es invisible para
// miembros y workers. Restore/purge se manejan en queries /admin/*.
func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdByIDIncludingDeleted = `-- name: GetHouseholdByIDIncludingDeleted :one
SELECT id, name, base_currency, created_by, created_at, updated_at, deleted_at FROM households WHERE id = $1
`

// Versión "admin": devuelve la fila incluso si está soft-deleted. Usada
// solo por los endpoints /admin/* (restore, purge).
func (q *Queries) GetHouseholdByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByIDIncludingDeleted, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdMemberRole = `-- name: GetHouseholdMemberRole :one
SELECT role
FROM household_members
WHERE household_id = $1 AND user_id = $2
`

type GetHouseholdMemberRoleParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Devuelve el rol del user en el household. Usada para chequear owner
// antes de operaciones privilegiadas (editar/borrar hogar, invitar).
// Si no es miembro devuelve pgx.ErrNoRows (el repo lo mapea a ErrNotFound).
func (q *Queries) GetHouseholdMemberRole(ctx context.Context, arg GetHouseholdMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getHouseholdMemberRole, arg.HouseholdID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isHouseholdMember = `-- name: IsHouseholdMember :one
SELECT EXISTS (
    SELECT 1 FROM household_members hm
    INNER JOIN households h ON h.id = hm.household_id
    WHERE hm.household_id = $1 AND hm.user_id = $2 AND h.deleted_at IS NULL
) AS is_member
`

type IsHouseholdMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Devuelve true si el user pertenece al hogar Y el hogar no está soft-deleted.
// Un hogar borrado se comporta como si no existiera para todos los endpoints
// del API. Esto es lo que garantiza que los miembros pierden acceso al instante
// cuando el owner hace DELETE.
func (q *Queries) IsHouseholdMember(ctx context.Context, arg IsHouseholdMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isHouseholdMember, arg.HouseholdID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listAllHouseholdIDs = `-- name: ListAllHouseholdIDs :many
SELECT id FROM households WHERE deleted_at IS NULL
`

// Para workers que iteran todos los hogares (insights, reports). Saltea
// soft-deleted: un hogar borrado no debe generar insights ni reports.
func (q *Queries) ListAllHouseholdIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllHouseholdIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedHouseholds = `-- name: ListDeletedHouseholds :many
SELECT
    h.id,
    h.name,
    h.base_currency,
    h.created_by,
    h.created_at,
    h.updated_at,
    h.deleted_at,
    COALESCE(owner_u.id, creator.id)            AS owner_id,
    COALESCE(owner_u.email, creator.email)      AS owner_email,
    COALESCE(owner_u.first_name, creator.first_name) AS owner_first_name,
    COALESCE(owner_u.last_name, creator.last_name)   AS owner_last_name
FROM households h
INNER JOIN users creator ON creator.id = h.created_by
LEFT JOIN household_members hm ON hm.household_id = h.id AND hm.role = 'owner'
LEFT JOIN users owner_u ON owner_u.id = hm.user_id
WHERE h.deleted_at IS NOT NULL
ORDER BY h.deleted_at DESC
`

type ListDeletedHouseholdsRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	BaseCurrency   string             `json:"base_currency"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	OwnerEmail     string             `json:"owner_email"`
	OwnerFirstName string             `json:"owner_first_name"`
	OwnerLastName  string             `json:"owner_last_name"`
}

// Para /admin/households/deleted: lista todos los hogares soft-deleted
// ordenados por fecha de borrado (más reciente primero). JOIN con users
// para devolver info del owner actual (preferimos el owner vigente en
// household_members sobre created_by, porque pudo haber habido transfer).
//
// COALESCE: si no hay owner actual (caso raro de data inconsistente),
// cae al created_by para no perder la referencia.
func (q *Queries) ListDeletedHouseholds(ctx context.Context) ([]ListDeletedHouseholdsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedHouseholdsRow{}
	for rows.Next() {
		var i ListDeletedHouseholdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCurrency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.OwnerFirstName,
			&i.OwnerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdMembers = `-- name: ListHouseholdMembers :many
SELECT u.id, u.email, u.password_hash, u.created_at, u.updated_at, u.first_name, u.last_name, u.deleted_at, u.email_verified_at, u.is_superadmin, hm.role, hm.joined_at
FROM household_members hm
INNER JOIN users u ON u.id = hm.user_id
WHERE hm.household_id = $1
ORDER BY hm.joined_at ASC
`

type ListHouseholdMembersRow struct {
	User     User               `json:"user"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

// Devuelve los miembros con el nombre/email del user (JOIN).
// Usamos sqlc.embed(u) para que genere un struct anidado con todo user,
// así el handler puede devolver la info combinada sin queries extra.
func (q *Queries) ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]ListHouseholdMembersRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdMembersRow{}
	for rows.Next() {
		var i ListHouseholdMembersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.DeletedAt,
			&i.User.EmailVerifiedAt,
			&i.User.IsSuperadmin,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForUser = `-- name: ListHouseholdsForUser :many
SELECT h.id, h.name, h.base_currency, h.created_by, h.created_at, h.updated_at, h.deleted_at
FROM households h
INNER JOIN household_members hm ON hm.household_id = h.id
WHERE hm.user_id = $1 AND h.deleted_at IS NULL
ORDER BY h.created_at ASC
`

// Lista todos los hogares a los que pertenece un user. Filtra soft-deleted
// para que el user no vea hogares que fueron "borrados" (aunque siga su
// membresía en la tabla).
func (q *Queries) ListHouseholdsForUser(ctx context.Context, userID uuid.UUID) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCurrency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeHousehold = `-- name: PurgeHousehold :exec
DELETE FROM households WHERE id = $1
`

// Admin-only: borrado físico. ON DELETE CASCADE arrastra miembros,
// expenses, goals, settlements, split_rules, categories, invites. Irreversible.
func (q *Queries) PurgeHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, purgeHousehold, id)
	return err
}

const removeAllMembershipsForUser = `-- name: RemoveAllMembershipsForUser :exec
DELETE FROM household_members WHERE user_id = $1
`

// Usado en DELETE /me: desvincula al user de todos los hogares. El caller
// ya validó que no es owner de ninguno (sino rechazamos la baja).
func (q *Queries) RemoveAllMembershipsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllMembershipsForUser, userID)
	return err
}

const removeHouseholdMember = `-- name: RemoveHouseholdMember :exec
DELETE FROM household_members
WHERE household_id = $1 AND user_id = $2
`

type RemoveHouseholdMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveHouseholdMember(ctx context.Context, arg RemoveHouseholdMemberParams) error {
	_, err := q.db.Exec(ctx, removeHouseholdMember, arg.HouseholdID, arg.UserID)
	return err
}

const restoreHousehold = `-- name: RestoreHousehold :exec
UPDATE households
SET deleted_at = NULL,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

// Admin-only: limpia deleted_at y deja el hogar accesible de nuevo.
func (q *Queries) RestoreHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreHousehold, id)
	return err
}

const softDeleteHousehold = `-- name: SoftDeleteHousehold :exec
UPDATE households
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Marca el hogar como borrado. Los miembros pierden acceso pero toda la
// data (expenses, goals, settlements, etc.) queda intacta. El superadmin
// puede restaurar o purgar desde /admin/*.
func (q *Queries) SoftDeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHousehold, id)
	return err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET name = $2,
    base_currency = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, base_currency, created_by, created_at, updated_at, deleted_at
`

type UpdateHouseholdParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	BaseCurrency string    `json:"base_currency"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold, arg.ID, arg.Name, arg.BaseCurrency)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateHouseholdMemberRole = `-- name: UpdateHouseholdMemberRole :one
UPDATE household_members
SET role = $3
WHERE household_id = $1 AND user_id = $2
RETURNING household_id, user_id, role, joined_at
`

type UpdateHouseholdMemberRoleParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

// Actualiza el rol de un miembro. Devuelve la fila o pgx.ErrNoRows si el
// par (household, user) no existe.
func (q *Queries) UpdateHouseholdMemberRole(ctx context.Context, arg UpdateHouseholdMemberRoleParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, updateHouseholdMemberRole, arg.HouseholdID, arg.UserID, arg.Role)
	var i HouseholdMember
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
