// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: household_invites.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHouseholdInvite = `-- name: CreateHouseholdInvite :one


INSERT INTO household_invites (household_id, email, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type CreateHouseholdInviteParams struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	Email       string             `json:"email"`
	TokenHash   string             `json:"token_hash"`
	InvitedBy   uuid.UUID          `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Queries de household_invites.
func (q *Queries) CreateHouseholdInvite(ctx context.Context, arg CreateHouseholdInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, createHouseholdInvite,
		arg.HouseholdID,
		arg.Email,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdInviteByID = `-- name: GetHouseholdInviteByID :one
SELECT id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM household_invites WHERE id = $1
`

func (q *Queries) GetHouseholdInviteByID(ctx context.Context, id uuid.UUID) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, getHouseholdInviteByID, id)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdInviteByTokenHash = `-- name: GetHouseholdInviteByTokenHash :one
SELECT id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM household_invites WHERE token_hash = $1
`

func (q *Queries) GetHouseholdInviteByTokenHash(ctx context.Context, tokenHash string) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, getHouseholdInviteByTokenHash, tokenHash)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitesForHousehold = `-- name: ListPendingInvitesForHousehold :many
SELECT id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
FROM household_invites
WHERE household_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

// Invitaciones activas (no aceptadas, no revocadas, no expiradas) de un hogar.
func (q *Queries) ListPendingInvitesForHousehold(ctx context.Context, householdID uuid.UUID) ([]HouseholdInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdInvite{}
	for rows.Next() {
		var i HouseholdInvite
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Email,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :one
UPDATE household_invites
SET accepted_at = now(),
    accepted_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type MarkInviteAcceptedParams struct {
	ID         uuid.UUID  `json:"id"`
	AcceptedBy *uuid.UUID `json:"accepted_by"`
}

func (q *Queries) MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, markInviteAccepted, arg.ID, arg.AcceptedBy)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const refreshInviteToken = `-- name: RefreshInviteToken :one
UPDATE household_invites
SET token_hash = $2,
    expires_at = $3
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
RETURNING id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type RefreshInviteTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Pisa el token_hash y expires_at de una invitación pendiente. Se usa para
// "reenviar" — genera un nuevo token, invalida implícitamente el anterior
// (el hash previo ya no existe) y extiende la ventana. Solo matchea si la
// invitación sigue pendiente (ni aceptada ni revocada).
func (q *Queries) RefreshInviteToken(ctx context.Context, arg RefreshInviteTokenParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, refreshInviteToken, arg.ID, arg.TokenHash, arg.ExpiresAt)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE household_invites
SET revoked_at = now()
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
RETURNING id, household_id, email, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

func (q *Queries) RevokeInvite(ctx context.Context, id uuid.UUID) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, id)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
