// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incomes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncomesByHousehold = `-- name: CountIncomesByHousehold :one
SELECT COUNT(*)::bigint
FROM incomes
WHERE household_id = $1
  AND ($2::uuid IS NULL OR received_by = $2::uuid)
  AND ($3::uuid IS NULL OR payment_method_id = $3::uuid)
  AND ($4::text IS NULL OR source = $4::text)
  AND ($5::date IS NULL OR received_at >= $5::date)
  AND ($6::date IS NULL OR received_at <= $6::date)
`

type CountIncomesByHouseholdParams struct {
	HouseholdID     uuid.UUID   `json:"household_id"`
	ReceivedBy      *uuid.UUID  `json:"received_by"`
	PaymentMethodID *uuid.UUID  `json:"payment_method_id"`
	Source          pgtype.Text `json:"source"`
	FromDate        pgtype.Date `json:"from_date"`
	ToDate          pgtype.Date `json:"to_date"`
}

func (q *Queries) CountIncomesByHousehold(ctx context.Context, arg CountIncomesByHouseholdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncomesByHousehold,
		arg.HouseholdID,
		arg.ReceivedBy,
		arg.PaymentMethodID,
		arg.Source,
		arg.FromDate,
		arg.ToDate,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createIncome = `-- name: CreateIncome :one

INSERT INTO incomes (
    household_id, received_by, payment_method_id,
    amount, currency, amount_base, base_currency, rate_used, rate_at,
    source, description, received_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, household_id, received_by, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, source, description, received_at, created_at
`

type CreateIncomeParams struct {
	HouseholdID     uuid.UUID          `json:"household_id"`
	ReceivedBy      uuid.UUID          `json:"received_by"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	AmountBase      pgtype.Numeric     `json:"amount_base"`
	BaseCurrency    string             `json:"base_currency"`
	RateUsed        pgtype.Numeric     `json:"rate_used"`
	RateAt          pgtype.Timestamptz `json:"rate_at"`
	Source          string             `json:"source"`
	Description     string             `json:"description"`
	ReceivedAt      pgtype.Date        `json:"received_at"`
}

// ===================== incomes =====================
func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.HouseholdID,
		arg.ReceivedBy,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.AmountBase,
		arg.BaseCurrency,
		arg.RateUsed,
		arg.RateAt,
		arg.Source,
		arg.Description,
		arg.ReceivedAt,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Source,
		&i.Description,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRecurringIncome = `-- name: CreateRecurringIncome :one

INSERT INTO recurring_incomes (
    household_id, received_by, payment_method_id,
    amount, currency, description, source,
    frequency, day_of_month, day_of_week, month_of_year,
    is_active, starts_at, ends_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, household_id, received_by, payment_method_id, amount, currency, description, source, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at
`

type CreateRecurringIncomeParams struct {
	HouseholdID     uuid.UUID      `json:"household_id"`
	ReceivedBy      uuid.UUID      `json:"received_by"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	Description     string         `json:"description"`
	Source          string         `json:"source"`
	Frequency       string         `json:"frequency"`
	DayOfMonth      pgtype.Int4    `json:"day_of_month"`
	DayOfWeek       pgtype.Int4    `json:"day_of_week"`
	MonthOfYear     pgtype.Int4    `json:"month_of_year"`
	IsActive        bool           `json:"is_active"`
	StartsAt        pgtype.Date    `json:"starts_at"`
	EndsAt          pgtype.Date    `json:"ends_at"`
}

// ===================== recurring_incomes =====================
func (q *Queries) CreateRecurringIncome(ctx context.Context, arg CreateRecurringIncomeParams) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, createRecurringIncome,
		arg.HouseholdID,
		arg.ReceivedBy,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Source,
		arg.Frequency,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.MonthOfYear,
		arg.IsActive,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Source,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM incomes WHERE id = $1
`

func (q *Queries) DeleteIncome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncome, id)
	return err
}

const deleteRecurringIncome = `-- name: DeleteRecurringIncome :exec
DELETE FROM recurring_incomes WHERE id = $1
`

func (q *Queries) DeleteRecurringIncome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecurringIncome, id)
	return err
}

const getIncomeByID = `-- name: GetIncomeByID :one
SELECT id, household_id, received_by, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, source, description, received_at, created_at FROM incomes WHERE id = $1
`

func (q *Queries) GetIncomeByID(ctx context.Context, id uuid.UUID) (Income, error) {
	row := q.db.QueryRow(ctx, getIncomeByID, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Source,
		&i.Description,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecurringIncomeByID = `-- name: GetRecurringIncomeByID :one
SELECT id, household_id, received_by, payment_method_id, amount, currency, description, source, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_incomes WHERE id = $1
`

func (q *Queries) GetRecurringIncomeByID(ctx context.Context, id uuid.UUID) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, getRecurringIncomeByID, id)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Source,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRecurringIncomes = `-- name: ListActiveRecurringIncomes :many
SELECT id, household_id, received_by, payment_method_id, amount, currency, description, source, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_incomes
WHERE is_active = true
  AND starts_at <= $1::date
  AND (ends_at IS NULL OR ends_at >= $1::date)
`

// Lo usa el worker cada tick: todas las plantillas activas cuyo rango
// (starts_at/ends_at) cubre la fecha target. El filtro fino de "toca hoy
// según frequency/day_of_*" se resuelve en Go para no complicar la query.
func (q *Queries) ListActiveRecurringIncomes(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringIncome, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringIncomes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringIncome{}
	for rows.Next() {
		var i RecurringIncome
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ReceivedBy,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Source,
			&i.Frequency,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.MonthOfYear,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.LastGenerated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByHousehold = `-- name: ListIncomesByHousehold :many
SELECT id, household_id, received_by, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, source, description, received_at, created_at
FROM incomes
WHERE household_id = $1
  AND ($4::uuid IS NULL OR received_by = $4::uuid)
  AND ($5::uuid IS NULL OR payment_method_id = $5::uuid)
  AND ($6::text IS NULL OR source = $6::text)
  AND ($7::date IS NULL OR received_at >= $7::date)
  AND ($8::date IS NULL OR received_at <= $8::date)
ORDER BY received_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListIncomesByHouseholdParams struct {
	HouseholdID     uuid.UUID   `json:"household_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	ReceivedBy      *uuid.UUID  `json:"received_by"`
	PaymentMethodID *uuid.UUID  `json:"payment_method_id"`
	Source          pgtype.Text `json:"source"`
	FromDate        pgtype.Date `json:"from_date"`
	ToDate          pgtype.Date `json:"to_date"`
}

// Filtros opcionales: receivedBy, paymentMethodId, source, desde/hasta.
func (q *Queries) ListIncomesByHousehold(ctx context.Context, arg ListIncomesByHouseholdParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByHousehold,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.ReceivedBy,
		arg.PaymentMethodID,
		arg.Source,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ReceivedBy,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.AmountBase,
			&i.BaseCurrency,
			&i.RateUsed,
			&i.RateAt,
			&i.Source,
			&i.Description,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringIncomesByHousehold = `-- name: ListRecurringIncomesByHousehold :many
SELECT id, household_id, received_by, payment_method_id, amount, currency, description, source, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_incomes
WHERE household_id = $1
ORDER BY is_active DESC, created_at DESC
`

func (q *Queries) ListRecurringIncomesByHousehold(ctx context.Context, householdID uuid.UUID) ([]RecurringIncome, error) {
	rows, err := q.db.Query(ctx, listRecurringIncomesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringIncome{}
	for rows.Next() {
		var i RecurringIncome
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ReceivedBy,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Source,
			&i.Frequency,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.MonthOfYear,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.LastGenerated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecurringIncomeGenerated = `-- name: MarkRecurringIncomeGenerated :exec
UPDATE recurring_incomes SET last_generated = $2::date WHERE id = $1
`

type MarkRecurringIncomeGeneratedParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 pgtype.Date `json:"column_2"`
}

// Lo llama el worker después de crear el income real. Marca last_generated
// para que el próximo tick del mismo día no vuelva a crear.
func (q *Queries) MarkRecurringIncomeGenerated(ctx context.Context, arg MarkRecurringIncomeGeneratedParams) error {
	_, err := q.db.Exec(ctx, markRecurringIncomeGenerated, arg.ID, arg.Column2)
	return err
}

const setRecurringIncomeActive = `-- name: SetRecurringIncomeActive :exec
UPDATE recurring_incomes SET is_active = $2 WHERE id = $1
`

type SetRecurringIncomeActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetRecurringIncomeActive(ctx context.Context, arg SetRecurringIncomeActiveParams) error {
	_, err := q.db.Exec(ctx, setRecurringIncomeActive, arg.ID, arg.IsActive)
	return err
}

const sumIncomesByHouseholdInRange = `-- name: SumIncomesByHouseholdInRange :one
SELECT COALESCE(SUM(amount_base), 0)::numeric AS total_base
FROM incomes
WHERE household_id = $1
  AND received_at >= $2::date
  AND received_at <= $3::date
`

type SumIncomesByHouseholdInRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// Para /totals/income: suma amount_base de todos los ingresos del hogar
// entre received_at >= from y received_at <= to. COALESCE a 0 si no hay
// filas (evita NULL en el tipo Numeric).
func (q *Queries) SumIncomesByHouseholdInRange(ctx context.Context, arg SumIncomesByHouseholdInRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumIncomesByHouseholdInRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes
SET source      = $2,
    description = $3,
    received_at = $4
WHERE id = $1
RETURNING id, household_id, received_by, payment_method_id, amount, currency, amount_base, base_currency, rate_used, rate_at, source, description, received_at, created_at
`

type UpdateIncomeParams struct {
	ID          uuid.UUID   `json:"id"`
	Source      string      `json:"source"`
	Description string      `json:"description"`
	ReceivedAt  pgtype.Date `json:"received_at"`
}

// Solo editamos lo "meta": source/description/received_at. El amount/currency
// quedan fijos — si está mal, borrar y recrear (misma regla que expenses).
func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.Source,
		arg.Description,
		arg.ReceivedAt,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.RateUsed,
		&i.RateAt,
		&i.Source,
		&i.Description,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRecurringIncome = `-- name: UpdateRecurringIncome :one
UPDATE recurring_incomes
SET amount        = $2,
    currency      = $3,
    description   = $4,
    source        = $5,
    frequency     = $6,
    day_of_month  = $7,
    day_of_week   = $8,
    month_of_year = $9,
    ends_at       = $10,
    payment_method_id = $11
WHERE id = $1
RETURNING id, household_id, received_by, payment_method_id, amount, currency, description, source, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at
`

type UpdateRecurringIncomeParams struct {
	ID              uuid.UUID      `json:"id"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	Description     string         `json:"description"`
	Source          string         `json:"source"`
	Frequency       string         `json:"frequency"`
	DayOfMonth      pgtype.Int4    `json:"day_of_month"`
	DayOfWeek       pgtype.Int4    `json:"day_of_week"`
	MonthOfYear     pgtype.Int4    `json:"month_of_year"`
	EndsAt          pgtype.Date    `json:"ends_at"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
}

func (q *Queries) UpdateRecurringIncome(ctx context.Context, arg UpdateRecurringIncomeParams) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, updateRecurringIncome,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Source,
		arg.Frequency,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.MonthOfYear,
		arg.EndsAt,
		arg.PaymentMethodID,
	)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ReceivedBy,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Source,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}
