// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insights.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesSpentAtRange = `-- name: CountExpensesSpentAtRange :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(DISTINCT category_id)::bigint AS distinct_categories
FROM expenses
WHERE household_id = $1
  AND spent_at >= $2::date
  AND spent_at <= $3::date
`

type CountExpensesSpentAtRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type CountExpensesSpentAtRangeRow struct {
	TotalCount         int64 `json:"total_count"`
	DistinctCategories int64 `json:"distinct_categories"`
}

// Cuántas transacciones hubo en el rango. Distinct categorías también.
func (q *Queries) CountExpensesSpentAtRange(ctx context.Context, arg CountExpensesSpentAtRangeParams) (CountExpensesSpentAtRangeRow, error) {
	row := q.db.QueryRow(ctx, countExpensesSpentAtRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var i CountExpensesSpentAtRangeRow
	err := row.Scan(&i.TotalCount, &i.DistinctCategories)
	return i, err
}

const countUnreadInsightsByHousehold = `-- name: CountUnreadInsightsByHousehold :one
SELECT COUNT(*)::bigint
FROM daily_insights
WHERE household_id = $1
  AND is_read = false
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
`

type CountUnreadInsightsByHouseholdParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
}

func (q *Queries) CountUnreadInsightsByHousehold(ctx context.Context, arg CountUnreadInsightsByHouseholdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadInsightsByHousehold, arg.HouseholdID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDailyInsight = `-- name: CreateDailyInsight :one

INSERT INTO daily_insights (
    household_id, user_id, insight_date, insight_type,
    title, body, severity, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (household_id, user_id, insight_date, insight_type) DO NOTHING
RETURNING id, household_id, user_id, insight_date, insight_type, title, body, severity, is_read, metadata, created_at
`

type CreateDailyInsightParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	UserID      *uuid.UUID  `json:"user_id"`
	InsightDate pgtype.Date `json:"insight_date"`
	InsightType string      `json:"insight_type"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	Severity    string      `json:"severity"`
	Metadata    []byte      `json:"metadata"`
}

// ===================== daily_insights =====================
// ON CONFLICT DO NOTHING: si ya existe un insight del mismo (household, user,
// date, type) lo dejamos intacto. El RETURNING puede ser vacío — el caller
// interpreta eso como "ya existía, skip".
func (q *Queries) CreateDailyInsight(ctx context.Context, arg CreateDailyInsightParams) (DailyInsight, error) {
	row := q.db.QueryRow(ctx, createDailyInsight,
		arg.HouseholdID,
		arg.UserID,
		arg.InsightDate,
		arg.InsightType,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.Metadata,
	)
	var i DailyInsight
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.InsightDate,
		&i.InsightType,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.IsRead,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDailyInsight = `-- name: DeleteDailyInsight :exec
DELETE FROM daily_insights WHERE id = $1
`

func (q *Queries) DeleteDailyInsight(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDailyInsight, id)
	return err
}

const getDailyInsightByID = `-- name: GetDailyInsightByID :one
SELECT id, household_id, user_id, insight_date, insight_type, title, body, severity, is_read, metadata, created_at FROM daily_insights WHERE id = $1
`

func (q *Queries) GetDailyInsightByID(ctx context.Context, id uuid.UUID) (DailyInsight, error) {
	row := q.db.QueryRow(ctx, getDailyInsightByID, id)
	var i DailyInsight
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.InsightDate,
		&i.InsightType,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.IsRead,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listDailyInsightsByHousehold = `-- name: ListDailyInsightsByHousehold :many
SELECT id, household_id, user_id, insight_date, insight_type, title, body, severity, is_read, metadata, created_at
FROM daily_insights
WHERE household_id = $1
  AND ($4::uuid IS NULL OR user_id = $4::uuid)
  AND ($5::boolean IS NULL OR is_read = NOT $5::boolean)
  AND ($6::date IS NULL OR insight_date >= $6::date)
  AND ($7::date IS NULL OR insight_date <= $7::date)
  AND ($8::text IS NULL OR insight_type = $8::text)
ORDER BY insight_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListDailyInsightsByHouseholdParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	UserID      *uuid.UUID  `json:"user_id"`
	OnlyUnread  pgtype.Bool `json:"only_unread"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	InsightType pgtype.Text `json:"insight_type"`
}

// Filtros opcionales: user_id (null = insights del hogar; uuid = de ese user),
// unread_only, rango de fechas, tipo.
func (q *Queries) ListDailyInsightsByHousehold(ctx context.Context, arg ListDailyInsightsByHouseholdParams) ([]DailyInsight, error) {
	rows, err := q.db.Query(ctx, listDailyInsightsByHousehold,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.OnlyUnread,
		arg.FromDate,
		arg.ToDate,
		arg.InsightType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyInsight{}
	for rows.Next() {
		var i DailyInsight
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.InsightDate,
			&i.InsightType,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.IsRead,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInsightsReadByHousehold = `-- name: MarkAllInsightsReadByHousehold :exec
UPDATE daily_insights
SET is_read = true
WHERE household_id = $1
  AND is_read = false
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
`

type MarkAllInsightsReadByHouseholdParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkAllInsightsReadByHousehold(ctx context.Context, arg MarkAllInsightsReadByHouseholdParams) error {
	_, err := q.db.Exec(ctx, markAllInsightsReadByHousehold, arg.HouseholdID, arg.UserID)
	return err
}

const markDailyInsightRead = `-- name: MarkDailyInsightRead :exec
UPDATE daily_insights SET is_read = true WHERE id = $1
`

func (q *Queries) MarkDailyInsightRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDailyInsightRead, id)
	return err
}

const sumExpensesSpentAtRange = `-- name: SumExpensesSpentAtRange :one

SELECT COALESCE(SUM(amount_base), 0)::numeric AS total_base
FROM expenses
WHERE household_id = $1
  AND spent_at >= $2::date
  AND spent_at <= $3::date
`

type SumExpensesSpentAtRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// ===================== agregaciones para generación =====================
// Gasto real (spent_at) del hogar en un rango. Base currency.
func (q *Queries) SumExpensesSpentAtRange(ctx context.Context, arg SumExpensesSpentAtRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumExpensesSpentAtRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const sumInstallmentsDueInRange = `-- name: SumInstallmentsDueInRange :one
SELECT COALESCE(SUM(i.installment_amount_base), 0)::numeric AS total_base
FROM expense_installments i
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND COALESCE(i.due_date, i.billing_date) >= $2::date
  AND COALESCE(i.due_date, i.billing_date) <= $3::date
`

type SumInstallmentsDueInRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// Cuotas cuyo due_date cae en el rango. Usamos COALESCE(due_date, billing_date)
// para unificar crédito y el resto.
func (q *Queries) SumInstallmentsDueInRange(ctx context.Context, arg SumInstallmentsDueInRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumInstallmentsDueInRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const topCategorySpentAtRange = `-- name: TopCategorySpentAtRange :one
SELECT e.category_id, COALESCE(SUM(e.amount_base), 0)::numeric AS total_base
FROM expenses e
WHERE e.household_id = $1
  AND e.spent_at >= $2::date
  AND e.spent_at <= $3::date
  AND e.category_id IS NOT NULL
GROUP BY e.category_id
ORDER BY total_base DESC
LIMIT 1
`

type TopCategorySpentAtRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type TopCategorySpentAtRangeRow struct {
	CategoryID *uuid.UUID     `json:"category_id"`
	TotalBase  pgtype.Numeric `json:"total_base"`
}

// Categoría con más gasto en el rango (spent_at). Devuelve también el total.
// Si no hay gastos, no devuelve filas (el caller lo maneja como "sin datos").
func (q *Queries) TopCategorySpentAtRange(ctx context.Context, arg TopCategorySpentAtRangeParams) (TopCategorySpentAtRangeRow, error) {
	row := q.db.QueryRow(ctx, topCategorySpentAtRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var i TopCategorySpentAtRangeRow
	err := row.Scan(&i.CategoryID, &i.TotalBase)
	return i, err
}
