// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bank struct {
	ID          uuid.UUID          `json:"id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Name        string             `json:"name"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BudgetGoal struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Scope        string             `json:"scope"`
	UserID       *uuid.UUID         `json:"user_id"`
	CategoryID   *uuid.UUID         `json:"category_id"`
	GoalType     string             `json:"goal_type"`
	TargetAmount pgtype.Numeric     `json:"target_amount"`
	Currency     string             `json:"currency"`
	Period       string             `json:"period"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	Color       string             `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CreditCard struct {
	ID                   uuid.UUID          `json:"id"`
	PaymentMethodID      uuid.UUID          `json:"payment_method_id"`
	Alias                string             `json:"alias"`
	LastFour             pgtype.Text        `json:"last_four"`
	DefaultClosingDay    int32              `json:"default_closing_day"`
	DefaultDueDay        int32              `json:"default_due_day"`
	DebitPaymentMethodID *uuid.UUID         `json:"debit_payment_method_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CreditCardPeriod struct {
	CreditCardID uuid.UUID          `json:"credit_card_id"`
	PeriodYm     string             `json:"period_ym"`
	ClosingDate  pgtype.Date        `json:"closing_date"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DailyInsight struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      *uuid.UUID         `json:"user_id"`
	InsightDate pgtype.Date        `json:"insight_date"`
	InsightType string             `json:"insight_type"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Severity    string             `json:"severity"`
	IsRead      bool               `json:"is_read"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExchangeRate struct {
	Currency   string             `json:"currency"`
	Source     string             `json:"source"`
	LastUpdate pgtype.Timestamptz `json:"last_update"`
	RateAvg    pgtype.Numeric     `json:"rate_avg"`
	RateBuy    pgtype.Numeric     `json:"rate_buy"`
	RateSell   pgtype.Numeric     `json:"rate_sell"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
}

type Expense struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CategoryID      *uuid.UUID         `json:"category_id"`
	PaymentMethodID uuid.UUID          `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	AmountBase      pgtype.Numeric     `json:"amount_base"`
	BaseCurrency    string             `json:"base_currency"`
	RateUsed        pgtype.Numeric     `json:"rate_used"`
	RateAt          pgtype.Timestamptz `json:"rate_at"`
	Description     string             `json:"description"`
	SpentAt         pgtype.Date        `json:"spent_at"`
	Installments    int32              `json:"installments"`
	IsShared        bool               `json:"is_shared"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseInstallment struct {
	ID                    uuid.UUID          `json:"id"`
	ExpenseID             uuid.UUID          `json:"expense_id"`
	InstallmentNumber     int32              `json:"installment_number"`
	InstallmentAmount     pgtype.Numeric     `json:"installment_amount"`
	InstallmentAmountBase pgtype.Numeric     `json:"installment_amount_base"`
	BillingDate           pgtype.Date        `json:"billing_date"`
	DueDate               pgtype.Date        `json:"due_date"`
	IsPaid                bool               `json:"is_paid"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseInstallmentShare struct {
	InstallmentID  uuid.UUID      `json:"installment_id"`
	UserID         uuid.UUID      `json:"user_id"`
	AmountBaseOwed pgtype.Numeric `json:"amount_base_owed"`
}

type Household struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	BaseCurrency string             `json:"base_currency"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HouseholdMember struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type HouseholdSplitRule struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Weight      pgtype.Numeric     `json:"weight"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Income struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	ReceivedBy      uuid.UUID          `json:"received_by"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	AmountBase      pgtype.Numeric     `json:"amount_base"`
	BaseCurrency    string             `json:"base_currency"`
	RateUsed        pgtype.Numeric     `json:"rate_used"`
	RateAt          pgtype.Timestamptz `json:"rate_at"`
	Source          string             `json:"source"`
	Description     string             `json:"description"`
	ReceivedAt      pgtype.Date        `json:"received_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PaymentMethod struct {
	ID                 uuid.UUID          `json:"id"`
	OwnerUserID        uuid.UUID          `json:"owner_user_id"`
	BankID             *uuid.UUID         `json:"bank_id"`
	Name               string             `json:"name"`
	Kind               string             `json:"kind"`
	AllowsInstallments bool               `json:"allows_installments"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type RecurringExpense struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CategoryID      *uuid.UUID         `json:"category_id"`
	PaymentMethodID uuid.UUID          `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	Description     string             `json:"description"`
	Installments    int32              `json:"installments"`
	IsShared        bool               `json:"is_shared"`
	Frequency       string             `json:"frequency"`
	DayOfMonth      pgtype.Int4        `json:"day_of_month"`
	DayOfWeek       pgtype.Int4        `json:"day_of_week"`
	MonthOfYear     pgtype.Int4        `json:"month_of_year"`
	IsActive        bool               `json:"is_active"`
	StartsAt        pgtype.Date        `json:"starts_at"`
	EndsAt          pgtype.Date        `json:"ends_at"`
	LastGenerated   pgtype.Date        `json:"last_generated"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RecurringIncome struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	ReceivedBy      uuid.UUID          `json:"received_by"`
	PaymentMethodID *uuid.UUID         `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	Description     string             `json:"description"`
	Source          string             `json:"source"`
	Frequency       string             `json:"frequency"`
	DayOfMonth      pgtype.Int4        `json:"day_of_month"`
	DayOfWeek       pgtype.Int4        `json:"day_of_week"`
	MonthOfYear     pgtype.Int4        `json:"month_of_year"`
	IsActive        bool               `json:"is_active"`
	StartsAt        pgtype.Date        `json:"starts_at"`
	EndsAt          pgtype.Date        `json:"ends_at"`
	LastGenerated   pgtype.Date        `json:"last_generated"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SettlementPayment struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	FromUser     uuid.UUID          `json:"from_user"`
	ToUser       uuid.UUID          `json:"to_user"`
	AmountBase   pgtype.Numeric     `json:"amount_base"`
	BaseCurrency string             `json:"base_currency"`
	Note         pgtype.Text        `json:"note"`
	PaidAt       pgtype.Date        `json:"paid_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
}
