// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one


INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries de password_resets.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_resets WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateActivePasswordResetsForUser = `-- name: InvalidateActivePasswordResetsForUser :exec
UPDATE password_resets
SET used_at = now()
WHERE user_id = $1
  AND used_at IS NULL
`

// Al emitir un nuevo token, invalidamos los anteriores del user (los
// marcamos como usados). Así el último mail es el único válido.
func (q *Queries) InvalidateActivePasswordResetsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateActivePasswordResetsForUser, userID)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :one
UPDATE password_resets
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

// Single-use: solo matchea si no fue usado aún y no expiró.
func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, markPasswordResetUsed, id)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
