// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_methods.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countActivePaymentMethodsByOwner = `-- name: CountActivePaymentMethodsByOwner :one
SELECT COUNT(*) AS total
FROM payment_methods
WHERE owner_user_id = $1 AND is_active = true
`

// Usada en validaciones: no dejar al user sin ningún método activo
// (Efectivo no se puede desactivar si es el último).
func (q *Queries) CountActivePaymentMethodsByOwner(ctx context.Context, ownerUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePaymentMethodsByOwner, ownerUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one


INSERT INTO payment_methods (owner_user_id, bank_id, name, kind, allows_installments)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at
`

type CreatePaymentMethodParams struct {
	OwnerUserID        uuid.UUID  `json:"owner_user_id"`
	BankID             *uuid.UUID `json:"bank_id"`
	Name               string     `json:"name"`
	Kind               string     `json:"kind"`
	AllowsInstallments bool       `json:"allows_installments"`
}

// Queries de payment_methods. Métodos de pago del user.
// Nunca se borran: toggle de is_active.
// Usado tanto por el endpoint público como por Register (para crear Efectivo).
// El CHECK del schema valida la combinación kind/allows_installments.
func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.OwnerUserID,
		arg.BankID,
		arg.Name,
		arg.Kind,
		arg.AllowsInstallments,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at FROM payment_methods WHERE id = $1
`

func (q *Queries) GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentMethodByOwnerAndName = `-- name: GetPaymentMethodByOwnerAndName :one
SELECT id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at FROM payment_methods
WHERE owner_user_id = $1 AND name = $2
LIMIT 1
`

type GetPaymentMethodByOwnerAndNameParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
}

// Busca por (owner, name) sin filtrar por is_active. El service la usa
// al crear un método: si encuentra una fila inactiva con ese nombre la
// reactiva ("revive") preservando id e historial de expenses.
func (q *Queries) GetPaymentMethodByOwnerAndName(ctx context.Context, arg GetPaymentMethodByOwnerAndNameParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByOwnerAndName, arg.OwnerUserID, arg.Name)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentMethodsByOwner = `-- name: ListPaymentMethodsByOwner :many
SELECT id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at FROM payment_methods
WHERE owner_user_id = $1 AND is_active = true
ORDER BY kind ASC, name ASC
`

// Lista los métodos activos del user. Orden: primero por kind (para
// agrupar visualmente), después por nombre.
func (q *Queries) ListPaymentMethodsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethodsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.BankID,
			&i.Name,
			&i.Kind,
			&i.AllowsInstallments,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivatePaymentMethod = `-- name: ReactivatePaymentMethod :one
UPDATE payment_methods
SET is_active           = true,
    bank_id             = $2,
    allows_installments = $3
WHERE id = $1
RETURNING id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at
`

type ReactivatePaymentMethodParams struct {
	ID                 uuid.UUID  `json:"id"`
	BankID             *uuid.UUID `json:"bank_id"`
	AllowsInstallments bool       `json:"allows_installments"`
}

// Marca is_active=true y actualiza los campos mutables (bank_id,
// allows_installments). kind es inmutable: si el user intenta crear con
// un kind distinto al del registro inactivo, el service rechaza antes
// de llamar acá, así que este UPDATE asume kind ya válido.
func (q *Queries) ReactivatePaymentMethod(ctx context.Context, arg ReactivatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, reactivatePaymentMethod, arg.ID, arg.BankID, arg.AllowsInstallments)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const setPaymentMethodActive = `-- name: SetPaymentMethodActive :one
UPDATE payment_methods
SET is_active = $2
WHERE id = $1
RETURNING id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at
`

type SetPaymentMethodActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetPaymentMethodActive(ctx context.Context, arg SetPaymentMethodActiveParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, setPaymentMethodActive, arg.ID, arg.IsActive)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET name = $2,
    bank_id = $3,
    allows_installments = $4
WHERE id = $1
RETURNING id, owner_user_id, bank_id, name, kind, allows_installments, is_active, created_at
`

type UpdatePaymentMethodParams struct {
	ID                 uuid.UUID  `json:"id"`
	Name               string     `json:"name"`
	BankID             *uuid.UUID `json:"bank_id"`
	AllowsInstallments bool       `json:"allows_installments"`
}

// Solo nombre, bank_id y allows_installments son editables.
// kind y owner_user_id son inmutables (cambiarlos rompería historial).
// El CHECK del schema se reevalúa en el UPDATE, así que intentar poner
// allows_installments=true en un debit/cash/transfer falla en DB.
func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.ID,
		arg.Name,
		arg.BankID,
		arg.AllowsInstallments,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.BankID,
		&i.Name,
		&i.Kind,
		&i.AllowsInstallments,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
