// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================================
	// household_members
	// ============================================================
	AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (HouseholdMember, error)
	// Queries de households y household_members.
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	// Queries sobre la tabla users.
	// Formato sqlc: cada query tiene una línea "-- name: NombreFuncion :tipo"
	// donde :tipo puede ser:
	//   :one   devuelve exactamente 1 fila
	//   :many  devuelve N filas ([]T)
	//   :exec  ejecuta sin devolver filas (INSERT/UPDATE/DELETE simple)
	//   :execrows  ejecuta y devuelve filas afectadas
	// Crea un usuario nuevo y devuelve la fila completa (para obtener id + timestamps).
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ON DELETE CASCADE en household_members → limpia la membresía automáticamente.
	DeleteHousehold(ctx context.Context, id uuid.UUID) error
	GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error)
	// Usado en login. Devuelve pgx.ErrNoRows si no existe → mapeamos a error de dominio.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Devuelve true si el user pertenece al hogar. Usada por el middleware de autz.
	IsHouseholdMember(ctx context.Context, arg IsHouseholdMemberParams) (bool, error)
	// Devuelve los miembros con el nombre/email del user (JOIN).
	// Usamos sqlc.embed(u) para que genere un struct anidado con todo user,
	// así el handler puede devolver la info combinada sin queries extra.
	ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]ListHouseholdMembersRow, error)
	// Lista todos los hogares a los que pertenece un user.
	// JOIN con household_members para filtrar por membresía.
	ListHouseholdsForUser(ctx context.Context, userID uuid.UUID) ([]Household, error)
	RemoveHouseholdMember(ctx context.Context, arg RemoveHouseholdMemberParams) error
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
