// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================
	// household_members
	// ============================================================
	AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (HouseholdMember, error)
	// Para la vista de matriz completa del hogar. Devuelve una fila por cada
	// par (debtor, creditor) con shares billed y settlements ya agregados.
	// El service combina las direcciones y netea.
	BalanceMatrixByHousehold(ctx context.Context, householdID uuid.UUID) ([]BalanceMatrixByHouseholdRow, error)
	// ===== balances (on-demand) =====
	// Devuelve cuánto debe `from_user` a `to_user` en el hogar, calculado on-demand.
	// Fórmula (ver sección 6 del plan):
	//   owed_by_from = SUM(shares.amount_base_owed) sobre expenses creados por to_user
	//                  con installment.billing_date <= CURRENT_DATE y share.user_id = from_user
	//   owed_by_to   = análoga en sentido inverso
	//   settled_fwd  = SUM(settlements from_user → to_user)
	//   settled_bwd  = SUM(settlements to_user → from_user)
	//   balance      = owed_by_from - owed_by_to - settled_fwd + settled_bwd
	// > 0 → from_user debe ese monto a to_user
	// < 0 → to_user debe a from_user (el signo lo resuelve el service)
	BalanceOwedBetween(ctx context.Context, arg BalanceOwedBetweenParams) (BalanceOwedBetweenRow, error)
	// Usada en validaciones: no dejar al user sin ningún método activo
	// (Efectivo no se puede desactivar si es el último).
	CountActivePaymentMethodsByOwner(ctx context.Context, ownerUserID uuid.UUID) (int64, error)
	CountExpensesByHousehold(ctx context.Context, arg CountExpensesByHouseholdParams) (int64, error)
	// Cuántas transacciones hubo en el rango. Distinct categorías también.
	CountExpensesSpentAtRange(ctx context.Context, arg CountExpensesSpentAtRangeParams) (CountExpensesSpentAtRangeRow, error)
	// Cuenta los owners vigentes de un hogar. Sirve para invariantes (ej:
	// no permitir demotions que dejen 0 owners).
	CountHouseholdOwners(ctx context.Context, householdID uuid.UUID) (int64, error)
	// Cuenta cuántos hogares tienen a este user como owner. Usado por la baja
	// de cuenta para exigir transferencia previa.
	CountHouseholdsOwnedByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountIncomesByHousehold(ctx context.Context, arg CountIncomesByHouseholdParams) (int64, error)
	CountUnreadInsightsByHousehold(ctx context.Context, arg CountUnreadInsightsByHouseholdParams) (int64, error)
	// Queries de banks. Los bancos son del user (owner_user_id),
	// nunca se borran: toggle de is_active.
	CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error)
	// ===================== budget_goals =====================
	CreateBudgetGoal(ctx context.Context, arg CreateBudgetGoalParams) (BudgetGoal, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Queries de credit_cards. 1-a-1 con payment_methods de kind='credit'.
	// Se crean siempre en la misma transacción que el payment_method (opción A).
	CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error)
	// ===================== daily_insights =====================
	// ON CONFLICT DO NOTHING: si ya existe un insight del mismo (household, user,
	// date, type) lo dejamos intacto. El RETURNING puede ser vacío — el caller
	// interpreta eso como "ya existía, skip".
	CreateDailyInsight(ctx context.Context, arg CreateDailyInsightParams) (DailyInsight, error)
	// Queries de email_verifications + flag de verificación en users.
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	// Queries de households y household_members.
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	// Queries de household_invites.
	CreateHouseholdInvite(ctx context.Context, arg CreateHouseholdInviteParams) (HouseholdInvite, error)
	// ===================== incomes =====================
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	// ===== installments =====
	CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (ExpenseInstallment, error)
	// ===== shares =====
	CreateInstallmentShare(ctx context.Context, arg CreateInstallmentShareParams) error
	// Queries de password_resets.
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	// Queries de payment_methods. Métodos de pago del user.
	// Nunca se borran: toggle de is_active.
	// Usado tanto por el endpoint público como por Register (para crear Efectivo).
	// El CHECK del schema valida la combinación kind/allows_installments.
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	// ===================== recurring_expenses =====================
	CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error)
	// ===================== recurring_incomes =====================
	CreateRecurringIncome(ctx context.Context, arg CreateRecurringIncomeParams) (RecurringIncome, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (SettlementPayment, error)
	// Queries sobre la tabla users.
	// Formato sqlc: cada query tiene una línea "-- name: NombreFuncion :tipo"
	// donde :tipo puede ser:
	//   :one   devuelve exactamente 1 fila
	//   :many  devuelve N filas ([]T)
	//   :exec  ejecuta sin devolver filas (INSERT/UPDATE/DELETE simple)
	//   :execrows  ejecuta y devuelve filas afectadas
	// Crea un usuario nuevo y devuelve la fila completa (para obtener id + timestamps).
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBudgetGoal(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCreditCardPeriod(ctx context.Context, arg DeleteCreditCardPeriodParams) error
	DeleteDailyInsight(ctx context.Context, id uuid.UUID) error
	DeleteExpense(ctx context.Context, id uuid.UUID) error
	DeleteIncome(ctx context.Context, id uuid.UUID) error
	DeleteRecurringExpense(ctx context.Context, id uuid.UUID) error
	DeleteRecurringIncome(ctx context.Context, id uuid.UUID) error
	DeleteSettlement(ctx context.Context, id uuid.UUID) error
	// Normalmente no se usa (al sacar miembro el CASCADE lo limpia), pero
	// lo expongo por simetría con el resto del CRUD.
	DeleteSplitRule(ctx context.Context, arg DeleteSplitRuleParams) error
	GetBankByID(ctx context.Context, id uuid.UUID) (Bank, error)
	// Usada por CreateBank para detectar un match inactivo y "revivirlo" en
	// vez de fallar por conflicto. El índice parcial (is_active=true) no
	// bloquea que existan inactivos con ese nombre.
	GetBankByOwnerAndName(ctx context.Context, arg GetBankByOwnerAndNameParams) (Bank, error)
	GetBudgetGoalByID(ctx context.Context, id uuid.UUID) (BudgetGoal, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	// Devuelve el detalle de tarjeta asociado al payment_method dado.
	// Si no existe (método no es credit) → pgx.ErrNoRows → repo mapea a ErrNotFound.
	GetCreditCardByPaymentMethodID(ctx context.Context, paymentMethodID uuid.UUID) (CreditCard, error)
	GetCreditCardPeriod(ctx context.Context, arg GetCreditCardPeriodParams) (CreditCardPeriod, error)
	GetDailyInsightByID(ctx context.Context, id uuid.UUID) (DailyInsight, error)
	GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error)
	GetExpenseByID(ctx context.Context, id uuid.UUID) (Expense, error)
	// Filtra soft-deleted: un hogar borrado por su owner es invisible para
	// miembros y workers. Restore/purge se manejan en queries /admin/*.
	GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error)
	// Versión "admin": devuelve la fila incluso si está soft-deleted. Usada
	// solo por los endpoints /admin/* (restore, purge).
	GetHouseholdByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Household, error)
	GetHouseholdInviteByID(ctx context.Context, id uuid.UUID) (HouseholdInvite, error)
	GetHouseholdInviteByTokenHash(ctx context.Context, tokenHash string) (HouseholdInvite, error)
	// Devuelve el rol del user en el household. Usada para chequear owner
	// antes de operaciones privilegiadas (editar/borrar hogar, invitar).
	// Si no es miembro devuelve pgx.ErrNoRows (el repo lo mapea a ErrNotFound).
	GetHouseholdMemberRole(ctx context.Context, arg GetHouseholdMemberRoleParams) (string, error)
	GetIncomeByID(ctx context.Context, id uuid.UUID) (Income, error)
	GetInstallmentByExpenseAndNumber(ctx context.Context, arg GetInstallmentByExpenseAndNumberParams) (ExpenseInstallment, error)
	GetLatestCreditCardPeriod(ctx context.Context, creditCardID uuid.UUID) (CreditCardPeriod, error)
	GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error)
	GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error)
	// Busca por (owner, name) sin filtrar por is_active. El service la usa
	// al crear un método: si encuentra una fila inactiva con ese nombre la
	// reactiva ("revive") preservando id e historial de expenses.
	GetPaymentMethodByOwnerAndName(ctx context.Context, arg GetPaymentMethodByOwnerAndNameParams) (PaymentMethod, error)
	GetRecurringExpenseByID(ctx context.Context, id uuid.UUID) (RecurringExpense, error)
	GetRecurringIncomeByID(ctx context.Context, id uuid.UUID) (RecurringIncome, error)
	GetSettlementByID(ctx context.Context, id uuid.UUID) (SettlementPayment, error)
	GetSplitRule(ctx context.Context, arg GetSplitRuleParams) (HouseholdSplitRule, error)
	// Usado en login. Devuelve pgx.ErrNoRows si no existe → mapeamos a error de dominio.
	// Filtra soft-deleted: un email anonimizado ya no matchea el formato original
	// pero además, aunque coincidiera, la fila queda invisible.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Filtra soft-deleted. Un token viejo de una cuenta borrada → pgx.ErrNoRows
	// → el middleware lo trata como sesión inválida.
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Al emitir un nuevo token, invalidamos los anteriores del user.
	InvalidateActiveEmailVerificationsForUser(ctx context.Context, userID uuid.UUID) error
	// Al emitir un nuevo token, invalidamos los anteriores del user (los
	// marcamos como usados). Así el último mail es el único válido.
	InvalidateActivePasswordResetsForUser(ctx context.Context, userID uuid.UUID) error
	// Devuelve true si el user pertenece al hogar Y el hogar no está soft-deleted.
	// Un hogar borrado se comporta como si no existiera para todos los endpoints
	// del API. Esto es lo que garantiza que los miembros pierden acceso al instante
	// cuando el owner hace DELETE.
	IsHouseholdMember(ctx context.Context, arg IsHouseholdMemberParams) (bool, error)
	// Flag global para gatear endpoints /admin/*. Independiente del rol por-hogar.
	// Se setea manualmente por DB; no hay endpoint para modificarlo.
	IsUserSuperadmin(ctx context.Context, id uuid.UUID) (bool, error)
	// Lo usa el worker: plantillas activas cuyo rango cubre `date`. Filtro fino
	// por frequency/day_of_* se resuelve en Go (mismo patrón que recurring_incomes).
	ListActiveRecurringExpenses(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringExpense, error)
	// Lo usa el worker cada tick: todas las plantillas activas cuyo rango
	// (starts_at/ends_at) cubre la fecha target. El filtro fino de "toca hoy
	// según frequency/day_of_*" se resuelve en Go para no complicar la query.
	ListActiveRecurringIncomes(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringIncome, error)
	// Para workers que iteran todos los hogares (insights, reports). Saltea
	// soft-deleted: un hogar borrado no debe generar insights ni reports.
	ListAllHouseholdIDs(ctx context.Context) ([]uuid.UUID, error)
	// Lista los bancos activos del user, orden estable por nombre.
	// Si algún día hace falta mostrar los desactivados, se agrega otra query.
	ListBanksByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Bank, error)
	// Filtros opcionales: scope, user_id (cuando scope='user'), is_active.
	ListBudgetGoalsByHousehold(ctx context.Context, arg ListBudgetGoalsByHouseholdParams) ([]BudgetGoal, error)
	ListCategoriesByHousehold(ctx context.Context, householdID uuid.UUID) ([]Category, error)
	ListCreditCardPeriods(ctx context.Context, creditCardID uuid.UUID) ([]CreditCardPeriod, error)
	// Lista las tarjetas activas del user con el payment_method embebido,
	// para evitar N+1 en el frontend (una sola llamada devuelve todo).
	// Filtra por payment_method.is_active = true: una tarjeta sin método
	// activo no se muestra.
	ListCreditCardsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListCreditCardsByOwnerRow, error)
	// Filtros opcionales: user_id (null = insights del hogar; uuid = de ese user),
	// unread_only, rango de fechas, tipo.
	ListDailyInsightsByHousehold(ctx context.Context, arg ListDailyInsightsByHouseholdParams) ([]DailyInsight, error)
	// Para /admin/households/deleted: lista todos los hogares soft-deleted
	// ordenados por fecha de borrado (más reciente primero). JOIN con users
	// para devolver info del owner actual (preferimos el owner vigente en
	// household_members sobre created_by, porque pudo haber habido transfer).
	//
	// COALESCE: si no hay owner actual (caso raro de data inconsistente),
	// cae al created_by para no perder la referencia.
	ListDeletedHouseholds(ctx context.Context) ([]ListDeletedHouseholdsRow, error)
	// Filtros opcionales: categoryId, paymentMethodId, desde/hasta (fechas).
	// Paginación por offset/limit simple. Cuando el volumen crezca, migrar a keyset.
	ListExpensesByHousehold(ctx context.Context, arg ListExpensesByHouseholdParams) ([]Expense, error)
	// Devuelve los miembros con el nombre/email del user (JOIN).
	// Usamos sqlc.embed(u) para que genere un struct anidado con todo user,
	// así el handler puede devolver la info combinada sin queries extra.
	ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]ListHouseholdMembersRow, error)
	// Lista todos los hogares a los que pertenece un user. Filtra soft-deleted
	// para que el user no vea hogares que fueron "borrados" (aunque siga su
	// membresía en la tabla).
	ListHouseholdsForUser(ctx context.Context, userID uuid.UUID) ([]Household, error)
	// Filtros opcionales: receivedBy, paymentMethodId, source, desde/hasta.
	ListIncomesByHousehold(ctx context.Context, arg ListIncomesByHouseholdParams) ([]Income, error)
	ListInstallmentsByExpense(ctx context.Context, expenseID uuid.UUID) ([]ExpenseInstallment, error)
	// Devuelve la última fila por (currency, source) usando DISTINCT ON.
	// Útil para el endpoint /current y para rehidratar el caché al arrancar.
	ListLatestExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	// Lista los métodos activos del user. Orden: primero por kind (para
	// agrupar visualmente), después por nombre.
	ListPaymentMethodsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]PaymentMethod, error)
	// Invitaciones activas (no aceptadas, no revocadas, no expiradas) de un hogar.
	ListPendingInvitesForHousehold(ctx context.Context, householdID uuid.UUID) ([]HouseholdInvite, error)
	ListRecurringExpensesByHousehold(ctx context.Context, householdID uuid.UUID) ([]RecurringExpense, error)
	ListRecurringIncomesByHousehold(ctx context.Context, householdID uuid.UUID) ([]RecurringIncome, error)
	// Filtros opcionales: from_user, to_user (para ver pagos entre dos miembros
	// específicos), desde/hasta. Paginación por offset/limit.
	ListSettlementsByHousehold(ctx context.Context, arg ListSettlementsByHouseholdParams) ([]SettlementPayment, error)
	ListSharesByExpense(ctx context.Context, expenseID uuid.UUID) ([]ExpenseInstallmentShare, error)
	ListSharesByInstallment(ctx context.Context, installmentID uuid.UUID) ([]ExpenseInstallmentShare, error)
	ListSplitRulesByHousehold(ctx context.Context, householdID uuid.UUID) ([]HouseholdSplitRule, error)
	MarkAllInsightsReadByHousehold(ctx context.Context, arg MarkAllInsightsReadByHouseholdParams) error
	MarkDailyInsightRead(ctx context.Context, id uuid.UUID) error
	// Single-use condicional: solo matchea si aún no fue usado y no expiró.
	MarkEmailVerificationUsed(ctx context.Context, id uuid.UUID) (EmailVerification, error)
	MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) (HouseholdInvite, error)
	// Single-use: solo matchea si no fue usado aún y no expiró.
	MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) (PasswordReset, error)
	MarkRecurringExpenseGenerated(ctx context.Context, arg MarkRecurringExpenseGeneratedParams) error
	// Lo llama el worker después de crear el income real. Marca last_generated
	// para que el próximo tick del mismo día no vuelva a crear.
	MarkRecurringIncomeGenerated(ctx context.Context, arg MarkRecurringIncomeGeneratedParams) error
	// Idempotente: si ya estaba verificado no hace nada.
	MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error
	// Admin-only: borrado físico. ON DELETE CASCADE arrastra miembros,
	// expenses, goals, settlements, split_rules, categories, invites. Irreversible.
	PurgeHousehold(ctx context.Context, id uuid.UUID) error
	// Marca is_active=true preservando id y created_at. Usada cuando el
	// user "crea" un banco cuyo nombre ya existe como inactivo del mismo owner.
	ReactivateBank(ctx context.Context, id uuid.UUID) (Bank, error)
	// Marca is_active=true y actualiza los campos mutables (bank_id,
	// allows_installments). kind es inmutable: si el user intenta crear con
	// un kind distinto al del registro inactivo, el service rechaza antes
	// de llamar acá, así que este UPDATE asume kind ya válido.
	ReactivatePaymentMethod(ctx context.Context, arg ReactivatePaymentMethodParams) (PaymentMethod, error)
	// Pisa el token_hash y expires_at de una invitación pendiente. Se usa para
	// "reenviar" — genera un nuevo token, invalida implícitamente el anterior
	// (el hash previo ya no existe) y extiende la ventana. Solo matchea si la
	// invitación sigue pendiente (ni aceptada ni revocada).
	RefreshInviteToken(ctx context.Context, arg RefreshInviteTokenParams) (HouseholdInvite, error)
	// Usado en DELETE /me: desvincula al user de todos los hogares. El caller
	// ya validó que no es owner de ninguno (sino rechazamos la baja).
	RemoveAllMembershipsForUser(ctx context.Context, userID uuid.UUID) error
	RemoveHouseholdMember(ctx context.Context, arg RemoveHouseholdMemberParams) error
	// Admin-only: limpia deleted_at y deja el hogar accesible de nuevo.
	RestoreHousehold(ctx context.Context, id uuid.UUID) error
	RevokeInvite(ctx context.Context, id uuid.UUID) (HouseholdInvite, error)
	// Activa o desactiva un banco. El ON DELETE SET NULL en payment_methods.bank_id
	// NO se dispara acá (no borramos la fila), así que los métodos siguen
	// asociados al banco aunque el banco esté inactivo.
	SetBankActive(ctx context.Context, arg SetBankActiveParams) (Bank, error)
	SetBudgetGoalActive(ctx context.Context, arg SetBudgetGoalActiveParams) error
	SetInstallmentPaid(ctx context.Context, arg SetInstallmentPaidParams) (ExpenseInstallment, error)
	SetPaymentMethodActive(ctx context.Context, arg SetPaymentMethodActiveParams) (PaymentMethod, error)
	SetRecurringExpenseActive(ctx context.Context, arg SetRecurringExpenseActiveParams) error
	SetRecurringIncomeActive(ctx context.Context, arg SetRecurringIncomeActiveParams) error
	// Agrega settlements por par (from, to) para la matriz.
	SettlementsByHouseholdAggregated(ctx context.Context, householdID uuid.UUID) ([]SettlementsByHouseholdAggregatedRow, error)
	// Marca el hogar como borrado. Los miembros pierden acceso pero toda la
	// data (expenses, goals, settlements, etc.) queda intacta. El superadmin
	// puede restaurar o purgar desde /admin/*.
	SoftDeleteHousehold(ctx context.Context, id uuid.UUID) error
	// Marca el user como borrado y anonimiza el email para liberar el UNIQUE
	// y permitir re-registro con el mismo email. El sufijo incluye el id
	// (único garantizado) + un dominio que no es deliverable.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// ===================== breakdown por categoría =====================
	// Para el resumen mensual: total por categoría usando spent_at.
	// Incluye categoría NULL (gastos sin categorizar). El JOIN es LEFT.
	SumExpensesByCategoryInRange(ctx context.Context, arg SumExpensesByCategoryInRangeParams) ([]SumExpensesByCategoryInRangeRow, error)
	// ===================== fijos vs variables =====================
	// Split por origen: gastos con recurring_expense_id NOT NULL son "fijos"
	// (los generó el worker de CP9); el resto son "variables" (entrada manual).
	SumExpensesFixedVariableInRange(ctx context.Context, arg SumExpensesFixedVariableInRangeParams) (SumExpensesFixedVariableInRangeRow, error)
	// ===================== trends por mes =====================
	// Para gráfico de trends: total por mes en los últimos N meses.
	// El caller pasa from/to calculados (start del mes más viejo ~ end del actual).
	// date_trunc normaliza al primer día del mes.
	SumExpensesSpentAtByMonth(ctx context.Context, arg SumExpensesSpentAtByMonthParams) ([]SumExpensesSpentAtByMonthRow, error)
	// ===================== reports: triada spent/billed/due =====================
	// "spent_this_month": lo que se compró/decidió gastar en el rango.
	SumExpensesSpentAtForReport(ctx context.Context, arg SumExpensesSpentAtForReportParams) (pgtype.Numeric, error)
	// ===================== agregaciones para generación =====================
	// Gasto real (spent_at) del hogar en un rango. Base currency.
	SumExpensesSpentAtRange(ctx context.Context, arg SumExpensesSpentAtRangeParams) (pgtype.Numeric, error)
	// Para /totals/income: suma amount_base de todos los ingresos del hogar
	// entre received_at >= from y received_at <= to. COALESCE a 0 si no hay
	// filas (evita NULL en el tipo Numeric).
	SumIncomesByHouseholdInRange(ctx context.Context, arg SumIncomesByHouseholdInRangeParams) (pgtype.Numeric, error)
	// Para savings scope=user: total de ingresos de un usuario en el período.
	SumIncomesByUserInRange(ctx context.Context, arg SumIncomesByUserInRangeParams) (pgtype.Numeric, error)
	// Ingresos por mes para comparar contra gastos en trends.
	SumIncomesReceivedByMonth(ctx context.Context, arg SumIncomesReceivedByMonthParams) ([]SumIncomesReceivedByMonthRow, error)
	// "billed_this_month": lo que apareció en resúmenes de tarjeta en el rango
	// (billing_date). Para no-crédito es igual a spent_at (la query no distingue).
	SumInstallmentsBilledForReport(ctx context.Context, arg SumInstallmentsBilledForReportParams) (pgtype.Numeric, error)
	// Mismo concepto pero por due_date — lo que hay que pagar por mes.
	SumInstallmentsDueByMonth(ctx context.Context, arg SumInstallmentsDueByMonthParams) ([]SumInstallmentsDueByMonthRow, error)
	// "due_this_month": lo que hay que pagar en el rango (due_date). Para
	// no-crédito due_date es NULL, usamos COALESCE con billing_date.
	SumInstallmentsDueForReport(ctx context.Context, arg SumInstallmentsDueForReportParams) (pgtype.Numeric, error)
	// Cuotas cuyo due_date cae en el rango. Usamos COALESCE(due_date, billing_date)
	// para unificar crédito y el resto.
	SumInstallmentsDueInRange(ctx context.Context, arg SumInstallmentsDueInRangeParams) (pgtype.Numeric, error)
	// ===================== progress helpers =====================
	// Suma base de cuotas del hogar dentro del período, filtrando por categoría
	// opcional. Usa COALESCE(due_date, billing_date): crédito cuenta cuando vence,
	// el resto cuando se pagó (billing_date = spent_at).
	SumInstallmentsForHouseholdGoal(ctx context.Context, arg SumInstallmentsForHouseholdGoalParams) (pgtype.Numeric, error)
	// Suma la porción del usuario en cuotas del hogar dentro del período.
	// Para gastos compartidos: usa expense_installment_shares.
	// Para gastos NO compartidos (is_shared=false): cuenta el total si el usuario
	// es created_by, porque no hay filas de shares.
	SumInstallmentsForUserGoal(ctx context.Context, arg SumInstallmentsForUserGoalParams) (pgtype.Numeric, error)
	// Categoría con más gasto en el rango (spent_at). Devuelve también el total.
	// Si no hay gastos, no devuelve filas (el caller lo maneja como "sin datos").
	TopCategorySpentAtRange(ctx context.Context, arg TopCategorySpentAtRangeParams) (TopCategorySpentAtRangeRow, error)
	// Solo permite cambiar el nombre (único campo editable del modelo).
	UpdateBankName(ctx context.Context, arg UpdateBankNameParams) (Bank, error)
	// No dejamos cambiar scope/user_id/goal_type — si hay que migrar, borrar y crear.
	UpdateBudgetGoal(ctx context.Context, arg UpdateBudgetGoalParams) (BudgetGoal, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// Alias, last_four y ciclo son editables. payment_method_id es inmutable.
	// debit_payment_method_id cambiable (ej: cambiás la cuenta de débito automático).
	// La validación "mismo owner / no auto-referencia" se hace en el service.
	UpdateCreditCard(ctx context.Context, arg UpdateCreditCardParams) (CreditCard, error)
	// Solo campos editables: description, spent_at, category_id.
	// amount/currency/installments NO se editan (borrar y recrear).
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	// Actualiza el rol de un miembro. Devuelve la fila o pgx.ErrNoRows si el
	// par (household, user) no existe.
	UpdateHouseholdMemberRole(ctx context.Context, arg UpdateHouseholdMemberRoleParams) (HouseholdMember, error)
	// Solo editamos lo "meta": source/description/received_at. El amount/currency
	// quedan fijos — si está mal, borrar y recrear (misma regla que expenses).
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateInstallmentDates(ctx context.Context, arg UpdateInstallmentDatesParams) (ExpenseInstallment, error)
	// Solo nombre, bank_id y allows_installments son editables.
	// kind y owner_user_id son inmutables (cambiarlos rompería historial).
	// El CHECK del schema se reevalúa en el UPDATE, así que intentar poner
	// allows_installments=true en un debit/cash/transfer falla en DB.
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error)
	UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error)
	UpdateRecurringIncome(ctx context.Context, arg UpdateRecurringIncomeParams) (RecurringIncome, error)
	// Actualiza nombre y apellido juntos (si se edita uno se reenvían ambos).
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Actualiza nombre/apellido/email en una sola query. El caller es
	// responsable de validar cada uno antes. La colisión de email la captura
	// el UNIQUE constraint y se mapea a ErrConflict en el repo.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertCreditCardPeriod(ctx context.Context, arg UpsertCreditCardPeriodParams) (CreditCardPeriod, error)
	// El worker corre cada 15min aunque bluelytics no tenga dato nuevo
	// (fines de semana, feriados). ON CONFLICT DO NOTHING evita duplicar.
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
	// Usado al bootstrappear un hogar (owner) y al sumar miembros (weight=1.0).
	// También desde PATCH /households/{id}/split cuando el owner edita pesos.
	UpsertSplitRule(ctx context.Context, arg UpsertSplitRuleParams) (HouseholdSplitRule, error)
}

var _ Querier = (*Queries)(nil)
