// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_expenses.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one

INSERT INTO recurring_expenses (
    household_id, created_by, category_id, payment_method_id,
    amount, currency, description, installments, is_shared,
    frequency, day_of_month, day_of_week, month_of_year,
    is_active, starts_at, ends_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, household_id, created_by, category_id, payment_method_id, amount, currency, description, installments, is_shared, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at
`

type CreateRecurringExpenseParams struct {
	HouseholdID     uuid.UUID      `json:"household_id"`
	CreatedBy       uuid.UUID      `json:"created_by"`
	CategoryID      *uuid.UUID     `json:"category_id"`
	PaymentMethodID uuid.UUID      `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	Description     string         `json:"description"`
	Installments    int32          `json:"installments"`
	IsShared        bool           `json:"is_shared"`
	Frequency       string         `json:"frequency"`
	DayOfMonth      pgtype.Int4    `json:"day_of_month"`
	DayOfWeek       pgtype.Int4    `json:"day_of_week"`
	MonthOfYear     pgtype.Int4    `json:"month_of_year"`
	IsActive        bool           `json:"is_active"`
	StartsAt        pgtype.Date    `json:"starts_at"`
	EndsAt          pgtype.Date    `json:"ends_at"`
}

// ===================== recurring_expenses =====================
func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.HouseholdID,
		arg.CreatedBy,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Installments,
		arg.IsShared,
		arg.Frequency,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.MonthOfYear,
		arg.IsActive,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Installments,
		&i.IsShared,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses WHERE id = $1
`

func (q *Queries) DeleteRecurringExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpense, id)
	return err
}

const getRecurringExpenseByID = `-- name: GetRecurringExpenseByID :one
SELECT id, household_id, created_by, category_id, payment_method_id, amount, currency, description, installments, is_shared, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_expenses WHERE id = $1
`

func (q *Queries) GetRecurringExpenseByID(ctx context.Context, id uuid.UUID) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByID, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Installments,
		&i.IsShared,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRecurringExpenses = `-- name: ListActiveRecurringExpenses :many
SELECT id, household_id, created_by, category_id, payment_method_id, amount, currency, description, installments, is_shared, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_expenses
WHERE is_active = true
  AND starts_at <= $1::date
  AND (ends_at IS NULL OR ends_at >= $1::date)
`

// Lo usa el worker: plantillas activas cuyo rango cubre `date`. Filtro fino
// por frequency/day_of_* se resuelve en Go (mismo patrón que recurring_incomes).
func (q *Queries) ListActiveRecurringExpenses(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringExpenses, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CreatedBy,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Installments,
			&i.IsShared,
			&i.Frequency,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.MonthOfYear,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.LastGenerated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpensesByHousehold = `-- name: ListRecurringExpensesByHousehold :many
SELECT id, household_id, created_by, category_id, payment_method_id, amount, currency, description, installments, is_shared, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at FROM recurring_expenses
WHERE household_id = $1
ORDER BY is_active DESC, created_at DESC
`

func (q *Queries) ListRecurringExpensesByHousehold(ctx context.Context, householdID uuid.UUID) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listRecurringExpensesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.CreatedBy,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Installments,
			&i.IsShared,
			&i.Frequency,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.MonthOfYear,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.LastGenerated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecurringExpenseGenerated = `-- name: MarkRecurringExpenseGenerated :exec
UPDATE recurring_expenses SET last_generated = $2::date WHERE id = $1
`

type MarkRecurringExpenseGeneratedParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) MarkRecurringExpenseGenerated(ctx context.Context, arg MarkRecurringExpenseGeneratedParams) error {
	_, err := q.db.Exec(ctx, markRecurringExpenseGenerated, arg.ID, arg.Column2)
	return err
}

const setRecurringExpenseActive = `-- name: SetRecurringExpenseActive :exec
UPDATE recurring_expenses SET is_active = $2 WHERE id = $1
`

type SetRecurringExpenseActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetRecurringExpenseActive(ctx context.Context, arg SetRecurringExpenseActiveParams) error {
	_, err := q.db.Exec(ctx, setRecurringExpenseActive, arg.ID, arg.IsActive)
	return err
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses
SET amount            = $2,
    currency          = $3,
    description       = $4,
    installments      = $5,
    is_shared         = $6,
    frequency         = $7,
    day_of_month      = $8,
    day_of_week       = $9,
    month_of_year     = $10,
    ends_at           = $11,
    category_id       = $12,
    payment_method_id = $13
WHERE id = $1
RETURNING id, household_id, created_by, category_id, payment_method_id, amount, currency, description, installments, is_shared, frequency, day_of_month, day_of_week, month_of_year, is_active, starts_at, ends_at, last_generated, created_at
`

type UpdateRecurringExpenseParams struct {
	ID              uuid.UUID      `json:"id"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	Description     string         `json:"description"`
	Installments    int32          `json:"installments"`
	IsShared        bool           `json:"is_shared"`
	Frequency       string         `json:"frequency"`
	DayOfMonth      pgtype.Int4    `json:"day_of_month"`
	DayOfWeek       pgtype.Int4    `json:"day_of_week"`
	MonthOfYear     pgtype.Int4    `json:"month_of_year"`
	EndsAt          pgtype.Date    `json:"ends_at"`
	CategoryID      *uuid.UUID     `json:"category_id"`
	PaymentMethodID uuid.UUID      `json:"payment_method_id"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Installments,
		arg.IsShared,
		arg.Frequency,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.MonthOfYear,
		arg.EndsAt,
		arg.CategoryID,
		arg.PaymentMethodID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Installments,
		&i.IsShared,
		&i.Frequency,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.MonthOfYear,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.LastGenerated,
		&i.CreatedAt,
	)
	return i, err
}
