// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const sumExpensesByCategoryInRange = `-- name: SumExpensesByCategoryInRange :many

SELECT
    e.category_id,
    c.name::text AS category_name,
    COALESCE(SUM(e.amount_base), 0)::numeric AS total_base,
    COUNT(*)::bigint AS tx_count
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.household_id = $1
  AND e.spent_at >= $2::date
  AND e.spent_at <= $3::date
GROUP BY e.category_id, c.name
ORDER BY total_base DESC
`

type SumExpensesByCategoryInRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type SumExpensesByCategoryInRangeRow struct {
	CategoryID   *uuid.UUID     `json:"category_id"`
	CategoryName string         `json:"category_name"`
	TotalBase    pgtype.Numeric `json:"total_base"`
	TxCount      int64          `json:"tx_count"`
}

// ===================== breakdown por categoría =====================
// Para el resumen mensual: total por categoría usando spent_at.
// Incluye categoría NULL (gastos sin categorizar). El JOIN es LEFT.
func (q *Queries) SumExpensesByCategoryInRange(ctx context.Context, arg SumExpensesByCategoryInRangeParams) ([]SumExpensesByCategoryInRangeRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategoryInRange, arg.HouseholdID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByCategoryInRangeRow{}
	for rows.Next() {
		var i SumExpensesByCategoryInRangeRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.TotalBase,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesFixedVariableInRange = `-- name: SumExpensesFixedVariableInRange :one

SELECT
    COALESCE(SUM(CASE WHEN recurring_expense_id IS NOT NULL THEN amount_base ELSE 0 END), 0)::numeric AS fixed_total,
    COALESCE(SUM(CASE WHEN recurring_expense_id IS NULL THEN amount_base ELSE 0 END), 0)::numeric AS variable_total,
    COUNT(*) FILTER (WHERE recurring_expense_id IS NOT NULL)::bigint AS fixed_count,
    COUNT(*) FILTER (WHERE recurring_expense_id IS NULL)::bigint AS variable_count
FROM expenses
WHERE household_id = $1
  AND spent_at >= $2::date
  AND spent_at <= $3::date
`

type SumExpensesFixedVariableInRangeParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type SumExpensesFixedVariableInRangeRow struct {
	FixedTotal    pgtype.Numeric `json:"fixed_total"`
	VariableTotal pgtype.Numeric `json:"variable_total"`
	FixedCount    int64          `json:"fixed_count"`
	VariableCount int64          `json:"variable_count"`
}

// ===================== fijos vs variables =====================
// Split por origen: gastos con recurring_expense_id NOT NULL son "fijos"
// (los generó el worker de CP9); el resto son "variables" (entrada manual).
func (q *Queries) SumExpensesFixedVariableInRange(ctx context.Context, arg SumExpensesFixedVariableInRangeParams) (SumExpensesFixedVariableInRangeRow, error) {
	row := q.db.QueryRow(ctx, sumExpensesFixedVariableInRange, arg.HouseholdID, arg.Column2, arg.Column3)
	var i SumExpensesFixedVariableInRangeRow
	err := row.Scan(
		&i.FixedTotal,
		&i.VariableTotal,
		&i.FixedCount,
		&i.VariableCount,
	)
	return i, err
}

const sumExpensesSpentAtByMonth = `-- name: SumExpensesSpentAtByMonth :many

SELECT
    date_trunc('month', spent_at)::date AS month,
    COALESCE(SUM(amount_base), 0)::numeric AS total_base,
    COUNT(*)::bigint AS tx_count
FROM expenses
WHERE household_id = $1
  AND spent_at >= $2::date
  AND spent_at <= $3::date
GROUP BY month
ORDER BY month ASC
`

type SumExpensesSpentAtByMonthParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type SumExpensesSpentAtByMonthRow struct {
	Month     pgtype.Date    `json:"month"`
	TotalBase pgtype.Numeric `json:"total_base"`
	TxCount   int64          `json:"tx_count"`
}

// ===================== trends por mes =====================
// Para gráfico de trends: total por mes en los últimos N meses.
// El caller pasa from/to calculados (start del mes más viejo ~ end del actual).
// date_trunc normaliza al primer día del mes.
func (q *Queries) SumExpensesSpentAtByMonth(ctx context.Context, arg SumExpensesSpentAtByMonthParams) ([]SumExpensesSpentAtByMonthRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesSpentAtByMonth, arg.HouseholdID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesSpentAtByMonthRow{}
	for rows.Next() {
		var i SumExpensesSpentAtByMonthRow
		if err := rows.Scan(&i.Month, &i.TotalBase, &i.TxCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesSpentAtForReport = `-- name: SumExpensesSpentAtForReport :one

SELECT COALESCE(SUM(amount_base), 0)::numeric AS total_base
FROM expenses
WHERE household_id = $1
  AND spent_at >= $2::date
  AND spent_at <= $3::date
`

type SumExpensesSpentAtForReportParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// ===================== reports: triada spent/billed/due =====================
// "spent_this_month": lo que se compró/decidió gastar en el rango.
func (q *Queries) SumExpensesSpentAtForReport(ctx context.Context, arg SumExpensesSpentAtForReportParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumExpensesSpentAtForReport, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const sumIncomesReceivedByMonth = `-- name: SumIncomesReceivedByMonth :many
SELECT
    date_trunc('month', received_at)::date AS month,
    COALESCE(SUM(amount_base), 0)::numeric AS total_base
FROM incomes
WHERE household_id = $1
  AND received_at >= $2::date
  AND received_at <= $3::date
GROUP BY month
ORDER BY month ASC
`

type SumIncomesReceivedByMonthParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type SumIncomesReceivedByMonthRow struct {
	Month     pgtype.Date    `json:"month"`
	TotalBase pgtype.Numeric `json:"total_base"`
}

// Ingresos por mes para comparar contra gastos en trends.
func (q *Queries) SumIncomesReceivedByMonth(ctx context.Context, arg SumIncomesReceivedByMonthParams) ([]SumIncomesReceivedByMonthRow, error) {
	rows, err := q.db.Query(ctx, sumIncomesReceivedByMonth, arg.HouseholdID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumIncomesReceivedByMonthRow{}
	for rows.Next() {
		var i SumIncomesReceivedByMonthRow
		if err := rows.Scan(&i.Month, &i.TotalBase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumInstallmentsBilledForReport = `-- name: SumInstallmentsBilledForReport :one
SELECT COALESCE(SUM(i.installment_amount_base), 0)::numeric AS total_base
FROM expense_installments i
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND i.billing_date >= $2::date
  AND i.billing_date <= $3::date
`

type SumInstallmentsBilledForReportParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// "billed_this_month": lo que apareció en resúmenes de tarjeta en el rango
// (billing_date). Para no-crédito es igual a spent_at (la query no distingue).
func (q *Queries) SumInstallmentsBilledForReport(ctx context.Context, arg SumInstallmentsBilledForReportParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumInstallmentsBilledForReport, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}

const sumInstallmentsDueByMonth = `-- name: SumInstallmentsDueByMonth :many
SELECT
    date_trunc('month', COALESCE(i.due_date, i.billing_date))::date AS month,
    COALESCE(SUM(i.installment_amount_base), 0)::numeric AS total_base
FROM expense_installments i
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND COALESCE(i.due_date, i.billing_date) >= $2::date
  AND COALESCE(i.due_date, i.billing_date) <= $3::date
GROUP BY month
ORDER BY month ASC
`

type SumInstallmentsDueByMonthParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

type SumInstallmentsDueByMonthRow struct {
	Month     pgtype.Date    `json:"month"`
	TotalBase pgtype.Numeric `json:"total_base"`
}

// Mismo concepto pero por due_date — lo que hay que pagar por mes.
func (q *Queries) SumInstallmentsDueByMonth(ctx context.Context, arg SumInstallmentsDueByMonthParams) ([]SumInstallmentsDueByMonthRow, error) {
	rows, err := q.db.Query(ctx, sumInstallmentsDueByMonth, arg.HouseholdID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumInstallmentsDueByMonthRow{}
	for rows.Next() {
		var i SumInstallmentsDueByMonthRow
		if err := rows.Scan(&i.Month, &i.TotalBase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumInstallmentsDueForReport = `-- name: SumInstallmentsDueForReport :one
SELECT COALESCE(SUM(i.installment_amount_base), 0)::numeric AS total_base
FROM expense_installments i
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND COALESCE(i.due_date, i.billing_date) >= $2::date
  AND COALESCE(i.due_date, i.billing_date) <= $3::date
`

type SumInstallmentsDueForReportParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Column2     pgtype.Date `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
}

// "due_this_month": lo que hay que pagar en el rango (due_date). Para
// no-crédito due_date es NULL, usamos COALESCE con billing_date.
func (q *Queries) SumInstallmentsDueForReport(ctx context.Context, arg SumInstallmentsDueForReportParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumInstallmentsDueForReport, arg.HouseholdID, arg.Column2, arg.Column3)
	var total_base pgtype.Numeric
	err := row.Scan(&total_base)
	return total_base, err
}
