// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlements.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const balanceMatrixByHousehold = `-- name: BalanceMatrixByHousehold :many
SELECT
    e.household_id,
    s.user_id      AS debtor_id,
    e.created_by   AS creditor_id,
    SUM(s.amount_base_owed)::numeric AS billed_owed
FROM expense_installment_shares s
JOIN expense_installments i ON i.id = s.installment_id
JOIN expenses e ON e.id = i.expense_id
WHERE e.household_id = $1
  AND i.billing_date <= CURRENT_DATE
  AND s.user_id <> e.created_by
GROUP BY e.household_id, s.user_id, e.created_by
`

type BalanceMatrixByHouseholdRow struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	DebtorID    uuid.UUID      `json:"debtor_id"`
	CreditorID  uuid.UUID      `json:"creditor_id"`
	BilledOwed  pgtype.Numeric `json:"billed_owed"`
}

// Para la vista de matriz completa del hogar. Devuelve una fila por cada
// par (debtor, creditor) con shares billed y settlements ya agregados.
// El service combina las direcciones y netea.
func (q *Queries) BalanceMatrixByHousehold(ctx context.Context, householdID uuid.UUID) ([]BalanceMatrixByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, balanceMatrixByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceMatrixByHouseholdRow{}
	for rows.Next() {
		var i BalanceMatrixByHouseholdRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.DebtorID,
			&i.CreditorID,
			&i.BilledOwed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const balanceOwedBetween = `-- name: BalanceOwedBetween :one

SELECT
    COALESCE((
        SELECT SUM(s.amount_base_owed)::numeric
        FROM expense_installment_shares s
        JOIN expense_installments i ON i.id = s.installment_id
        JOIN expenses e ON e.id = i.expense_id
        WHERE e.household_id = $1
          AND e.created_by = $2::uuid
          AND s.user_id = $3::uuid
          AND i.billing_date <= CURRENT_DATE
    ), 0)::numeric AS owed_by_from,
    COALESCE((
        SELECT SUM(s.amount_base_owed)::numeric
        FROM expense_installment_shares s
        JOIN expense_installments i ON i.id = s.installment_id
        JOIN expenses e ON e.id = i.expense_id
        WHERE e.household_id = $1
          AND e.created_by = $3::uuid
          AND s.user_id = $2::uuid
          AND i.billing_date <= CURRENT_DATE
    ), 0)::numeric AS owed_by_to,
    COALESCE((
        SELECT SUM(amount_base)::numeric
        FROM settlement_payments
        WHERE household_id = $1
          AND from_user = $3::uuid
          AND to_user = $2::uuid
    ), 0)::numeric AS settled_fwd,
    COALESCE((
        SELECT SUM(amount_base)::numeric
        FROM settlement_payments
        WHERE household_id = $1
          AND from_user = $2::uuid
          AND to_user = $3::uuid
    ), 0)::numeric AS settled_bwd
`

type BalanceOwedBetweenParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	ToUser      uuid.UUID `json:"to_user"`
	FromUser    uuid.UUID `json:"from_user"`
}

type BalanceOwedBetweenRow struct {
	OwedByFrom pgtype.Numeric `json:"owed_by_from"`
	OwedByTo   pgtype.Numeric `json:"owed_by_to"`
	SettledFwd pgtype.Numeric `json:"settled_fwd"`
	SettledBwd pgtype.Numeric `json:"settled_bwd"`
}

// ===== balances (on-demand) =====
// Devuelve cuánto debe `from_user` a `to_user` en el hogar, calculado on-demand.
// Fórmula (ver sección 6 del plan):
//
//	owed_by_from = SUM(shares.amount_base_owed) sobre expenses creados por to_user
//	               con installment.billing_date <= CURRENT_DATE y share.user_id = from_user
//	owed_by_to   = análoga en sentido inverso
//	settled_fwd  = SUM(settlements from_user → to_user)
//	settled_bwd  = SUM(settlements to_user → from_user)
//	balance      = owed_by_from - owed_by_to - settled_fwd + settled_bwd
//
// > 0 → from_user debe ese monto a to_user
// < 0 → to_user debe a from_user (el signo lo resuelve el service)
func (q *Queries) BalanceOwedBetween(ctx context.Context, arg BalanceOwedBetweenParams) (BalanceOwedBetweenRow, error) {
	row := q.db.QueryRow(ctx, balanceOwedBetween, arg.HouseholdID, arg.ToUser, arg.FromUser)
	var i BalanceOwedBetweenRow
	err := row.Scan(
		&i.OwedByFrom,
		&i.OwedByTo,
		&i.SettledFwd,
		&i.SettledBwd,
	)
	return i, err
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlement_payments (
    household_id, from_user, to_user, amount_base, base_currency, note, paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, from_user, to_user, amount_base, base_currency, note, paid_at, created_at
`

type CreateSettlementParams struct {
	HouseholdID  uuid.UUID      `json:"household_id"`
	FromUser     uuid.UUID      `json:"from_user"`
	ToUser       uuid.UUID      `json:"to_user"`
	AmountBase   pgtype.Numeric `json:"amount_base"`
	BaseCurrency string         `json:"base_currency"`
	Note         pgtype.Text    `json:"note"`
	PaidAt       pgtype.Date    `json:"paid_at"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (SettlementPayment, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.HouseholdID,
		arg.FromUser,
		arg.ToUser,
		arg.AmountBase,
		arg.BaseCurrency,
		arg.Note,
		arg.PaidAt,
	)
	var i SettlementPayment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.FromUser,
		&i.ToUser,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.Note,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSettlement = `-- name: DeleteSettlement :exec
DELETE FROM settlement_payments WHERE id = $1
`

func (q *Queries) DeleteSettlement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettlement, id)
	return err
}

const getSettlementByID = `-- name: GetSettlementByID :one
SELECT id, household_id, from_user, to_user, amount_base, base_currency, note, paid_at, created_at FROM settlement_payments WHERE id = $1
`

func (q *Queries) GetSettlementByID(ctx context.Context, id uuid.UUID) (SettlementPayment, error) {
	row := q.db.QueryRow(ctx, getSettlementByID, id)
	var i SettlementPayment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.FromUser,
		&i.ToUser,
		&i.AmountBase,
		&i.BaseCurrency,
		&i.Note,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSettlementsByHousehold = `-- name: ListSettlementsByHousehold :many
SELECT id, household_id, from_user, to_user, amount_base, base_currency, note, paid_at, created_at
FROM settlement_payments
WHERE household_id = $1
  AND ($4::uuid IS NULL OR from_user = $4::uuid)
  AND ($5::uuid IS NULL OR to_user = $5::uuid)
  AND ($6::date IS NULL OR paid_at >= $6::date)
  AND ($7::date IS NULL OR paid_at <= $7::date)
ORDER BY paid_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListSettlementsByHouseholdParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	FromUser    *uuid.UUID  `json:"from_user"`
	ToUser      *uuid.UUID  `json:"to_user"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

// Filtros opcionales: from_user, to_user (para ver pagos entre dos miembros
// específicos), desde/hasta. Paginación por offset/limit.
func (q *Queries) ListSettlementsByHousehold(ctx context.Context, arg ListSettlementsByHouseholdParams) ([]SettlementPayment, error) {
	rows, err := q.db.Query(ctx, listSettlementsByHousehold,
		arg.HouseholdID,
		arg.Limit,
		arg.Offset,
		arg.FromUser,
		arg.ToUser,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementPayment{}
	for rows.Next() {
		var i SettlementPayment
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.FromUser,
			&i.ToUser,
			&i.AmountBase,
			&i.BaseCurrency,
			&i.Note,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settlementsByHouseholdAggregated = `-- name: SettlementsByHouseholdAggregated :many
SELECT
    household_id,
    from_user,
    to_user,
    SUM(amount_base)::numeric AS paid_total
FROM settlement_payments
WHERE household_id = $1
GROUP BY household_id, from_user, to_user
`

type SettlementsByHouseholdAggregatedRow struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	FromUser    uuid.UUID      `json:"from_user"`
	ToUser      uuid.UUID      `json:"to_user"`
	PaidTotal   pgtype.Numeric `json:"paid_total"`
}

// Agrega settlements por par (from, to) para la matriz.
func (q *Queries) SettlementsByHouseholdAggregated(ctx context.Context, householdID uuid.UUID) ([]SettlementsByHouseholdAggregatedRow, error) {
	rows, err := q.db.Query(ctx, settlementsByHouseholdAggregated, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsByHouseholdAggregatedRow{}
	for rows.Next() {
		var i SettlementsByHouseholdAggregatedRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.FromUser,
			&i.ToUser,
			&i.PaidTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
