// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: split_rules.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSplitRule = `-- name: DeleteSplitRule :exec
DELETE FROM household_split_rules
WHERE household_id = $1 AND user_id = $2
`

type DeleteSplitRuleParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Normalmente no se usa (al sacar miembro el CASCADE lo limpia), pero
// lo expongo por simetría con el resto del CRUD.
func (q *Queries) DeleteSplitRule(ctx context.Context, arg DeleteSplitRuleParams) error {
	_, err := q.db.Exec(ctx, deleteSplitRule, arg.HouseholdID, arg.UserID)
	return err
}

const getSplitRule = `-- name: GetSplitRule :one
SELECT household_id, user_id, weight, updated_at FROM household_split_rules
WHERE household_id = $1 AND user_id = $2
`

type GetSplitRuleParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSplitRule(ctx context.Context, arg GetSplitRuleParams) (HouseholdSplitRule, error) {
	row := q.db.QueryRow(ctx, getSplitRule, arg.HouseholdID, arg.UserID)
	var i HouseholdSplitRule
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Weight,
		&i.UpdatedAt,
	)
	return i, err
}

const listSplitRulesByHousehold = `-- name: ListSplitRulesByHousehold :many
SELECT household_id, user_id, weight, updated_at FROM household_split_rules
WHERE household_id = $1
ORDER BY updated_at ASC
`

func (q *Queries) ListSplitRulesByHousehold(ctx context.Context, householdID uuid.UUID) ([]HouseholdSplitRule, error) {
	rows, err := q.db.Query(ctx, listSplitRulesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdSplitRule{}
	for rows.Next() {
		var i HouseholdSplitRule
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSplitRule = `-- name: UpsertSplitRule :one
INSERT INTO household_split_rules (household_id, user_id, weight)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, user_id) DO UPDATE
SET weight = EXCLUDED.weight,
    updated_at = NOW()
RETURNING household_id, user_id, weight, updated_at
`

type UpsertSplitRuleParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Weight      pgtype.Numeric `json:"weight"`
}

// Usado al bootstrappear un hogar (owner) y al sumar miembros (weight=1.0).
// También desde PATCH /households/{id}/split cuando el owner edita pesos.
func (q *Queries) UpsertSplitRule(ctx context.Context, arg UpsertSplitRuleParams) (HouseholdSplitRule, error) {
	row := q.db.QueryRow(ctx, upsertSplitRule, arg.HouseholdID, arg.UserID, arg.Weight)
	var i HouseholdSplitRule
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Weight,
		&i.UpdatedAt,
	)
	return i, err
}
