// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_identities.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :exec
INSERT INTO user_identities (provider, subject, user_id, email)
VALUES ($1, $2, $3, $4)
`

type CreateUserIdentityParams struct {
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
	UserID   uuid.UUID `json:"user_id"`
	Email    string    `json:"email"`
}

// Inserta la vinculación. Conflicto en PK (provider, subject) → ErrConflict
// (no debería darse en condiciones normales: si Get devolvió NotFound y
// alguien crea la misma identidad en paralelo, la segunda inserción falla).
func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error {
	_, err := q.db.Exec(ctx, createUserIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	return err
}

const getUserIdentity = `-- name: GetUserIdentity :one


SELECT provider, subject, user_id, email, linked_at
FROM user_identities
WHERE provider = $1 AND subject = $2
`

type GetUserIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

// Queries sobre la tabla user_identities (OAuth: hoy Google, mañana otros).
// (provider, subject) es PK; el matching de login pasa por acá.
// Lookup por (provider, subject). pgx.ErrNoRows si no existe → el service
// lo mapea a domain.ErrNotFound y arranca el flujo de auto-vinculación.
func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.LinkedAt,
	)
	return i, err
}

const listUserIdentitiesByUser = `-- name: ListUserIdentitiesByUser :many
SELECT provider, subject, email, linked_at
FROM user_identities
WHERE user_id = $1
ORDER BY linked_at ASC
`

type ListUserIdentitiesByUserRow struct {
	Provider string             `json:"provider"`
	Subject  string             `json:"subject"`
	Email    string             `json:"email"`
	LinkedAt pgtype.Timestamptz `json:"linked_at"`
}

// Para mostrar al user qué providers tiene vinculados en su perfil.
func (q *Queries) ListUserIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]ListUserIdentitiesByUserRow, error) {
	rows, err := q.db.Query(ctx, listUserIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserIdentitiesByUserRow{}
	for rows.Next() {
		var i ListUserIdentitiesByUserRow
		if err := rows.Scan(
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
